import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
  div24: {
    display: "grid",
    height: constants.paneToolbarHeight,
    flexShrink: 0,
    gridTemplateColumns: "minmax(0,1fr) auto",
    alignItems: "center",
    rowGap: "calc(0.25rem * 2)",
    columnGap: "calc(0.25rem * 2)",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderTopColor: tokens.border,
    borderRightColor: tokens.border,
    borderBottomColor: tokens.border,
    borderLeftColor: tokens.border,
    backgroundColor: tokens.colorHeader,
    paddingTop: "0px",
    paddingBottom: "0px",
    paddingLeft: {
      default: "calc(0.25rem * 3)",
      "@media (width >= 48rem)": "calc(0.25rem * 4)",
    },
    paddingRight: "calc(0.25rem * 2)",
    fontSize: "0.75rem",
  },
  div25: {
    display: "flex",
    minWidth: "0px",
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
  },
  button28: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    marginLeft: "calc(0.25rem * -1)",
    display: {
      default: "inline-flex",
      "@media (width >= 48rem)": "none",
    },
    height: "calc(0.25rem * 8)",
    width: "calc(0.25rem * 8)",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
    color: {
      default: tokens.dim,
      ":hover": tokens.fg,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  menu31: {
    pointerEvents: "none",
    height: "18px",
    width: "18px",
  },
  element47: {
    height: "calc(0.25rem * 7)",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    borderTopLeftRadius: "0.25rem",
    borderTopRightRadius: "0.25rem",
    borderBottomRightRadius: "0.25rem",
    borderBottomLeftRadius: "0.25rem",
    backgroundColor: tokens.surface,
    paddingLeft: "calc(0.25rem * 1.5)",
    paddingRight: "calc(0.25rem * 1.5)",
    paddingTop: "calc(0.25rem * 0.5)",
    paddingBottom: "calc(0.25rem * 0.5)",
    fontSize: constants.fsMd,
    fontWeight: 500,
    color: tokens.fg,
    outlineStyle: "none",
  },
  element57: {
    display: "block",
    minWidth: "0px",
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    borderTopLeftRadius: "0.25rem",
    borderTopRightRadius: "0.25rem",
    borderBottomRightRadius: "0.25rem",
    borderBottomLeftRadius: "0.25rem",
    textAlign: "left",
    fontSize: {
      default: constants.fsMd,
      "@media (width >= 48rem)": constants.fsBase,
    },
    fontWeight: 500,
    lineHeight: 1,
    color: tokens.fg,
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  rightpanelicon79: {
    display: "block",
    verticalAlign: "middle",
    pointerEvents: "none",
    height: "calc(0.25rem * 3.5)",
    width: "calc(0.25rem * 3.5)",
  },
  panelToggle: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    position: "relative",
    zIndex: 10,
    marginTop: "calc(0.25rem * -1)",
    marginBottom: "calc(0.25rem * -1)",
    display: "inline-flex",
    height: "calc(0.25rem * 8)",
    width: "calc(0.25rem * 8)",
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
  },
  panelToggleOpen: {
    color: tokens.fg,
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  panelToggleClosed: {
    color: {
      default: tokens.dim,
      ":hover": tokens.fg,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  lucideScale: {
    display: "block",
    verticalAlign: "middle",
    scale: constants.iconScale,
    transformOrigin: "center",
  },
});
