import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
  div28: {
    position: "relative",
    zIndex: 20,
    marginLeft: "auto",
    marginRight: "auto",
    marginTop: {
      default: "calc(0.25rem * 2)",
      "@media (width >= 40rem)": "calc(0.25rem * 2.5)",
    },
    display: "flex",
    width: {
      default: "100%",
      "@media (width >= 40rem)": "90%",
    },
    maxWidth: "calc(42rem * 0.9)",
    alignItems: "center",
    rowGap: "calc(0.25rem * 2)",
    columnGap: "calc(0.25rem * 2)",
    overflowX: "visible",
    overflowY: "visible",
    fontFamily: constants.fontMono,
    fontSize: constants.fsXs,
    color: tokens.dim,
  },
  div29: {
    display: "flex",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    alignItems: "center",
    rowGap: "calc(0.25rem * 2)",
    columnGap: "calc(0.25rem * 2)",
    overflowX: "visible",
    overflowY: "visible",
  },
  span30: {
    display: "block",
    minWidth: "0px",
    maxWidth: "42%",
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  span34: {
    display: "inline-flex",
    minWidth: "0px",
    flexShrink: 1,
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
  },
  gitbranchicon35: {
    display: "block",
    verticalAlign: "middle",
    height: "calc(0.25rem * 3)",
    width: "calc(0.25rem * 3)",
    flexShrink: 0,
  },
  span36: {
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  button43: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "inline-flex",
    flexShrink: 0,
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
    borderTopLeftRadius: "0.25rem",
    borderTopRightRadius: "0.25rem",
    borderBottomRightRadius: "0.25rem",
    borderBottomLeftRadius: "0.25rem",
    paddingLeft: "0.25rem",
    paddingRight: "0.25rem",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.fg05,
    },
  },
  span46: {
    color: tokens.ok,
  },
  span47: {
    color: tokens.err,
  },
  button54: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    marginLeft: "auto",
    display: "inline-flex",
    flexShrink: 0,
    alignItems: "center",
    borderTopLeftRadius: "0.25rem",
    borderTopRightRadius: "0.25rem",
    borderBottomRightRadius: "0.25rem",
    borderBottomLeftRadius: "0.25rem",
    paddingLeft: "0.25rem",
    paddingRight: "0.25rem",
    color: {
      default: tokens.dim,
      ":hover": tokens.fg80,
    },
  },
  span57: {
  },
  lucideScale: {
    display: "block",
    verticalAlign: "middle",
    scale: constants.iconScale,
    transformOrigin: "center",
  },
});
