import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
	details160: {
		color: tokens.fg80,
		opacity: "100%",
		minWidth: "0px",
	},
	summary162: {
		display: {
			default: "flex",
			"::-webkit-details-marker": "none",
		},
		minHeight: "calc(0.25rem * 6)",
		minWidth: "0px",
		cursor: "pointer",
		listStyleType: "none",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		paddingLeft: "calc(0.25rem * 1.5)",
		paddingRight: "calc(0.25rem * 1.5)",
		paddingTop: "calc(0.25rem * 0.5)",
		paddingBottom: "calc(0.25rem * 0.5)",
		backgroundColor: {
			default: "transparent",
			":hover": tokens.hover,
		},
	},
	icon168: {
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		flexShrink: 0,
		color: tokens.dim65,
	},
	span177: {
		minWidth: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontFamily: constants.fontMono,
		fontSize: "13px",
		lineHeight: "calc(0.25rem * 5)",
		color: tokens.hl2,
	},
	span181: {
		minWidth: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
	},
	chevronright184: {
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		flexShrink: 0,
		color: tokens.dim55,
		transitionProperty: "transform, translate, scale, rotate",
	},
	pre189: {
		display: { default: null, "::-webkit-scrollbar": "none" },
		scrollbarWidth: "none",
		marginBottom: "calc(0.25rem * 1.5)",
		marginLeft: "calc(0.25rem * 7)",
		marginTop: "0.25rem",
		maxHeight: "340px",
		maxWidth: "100%",
		overflowX: "auto",
		overflowY: "auto",
		whiteSpace: "pre-wrap",
		overflowWrap: "break-word",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.border,
		borderRightColor: tokens.border,
		borderBottomColor: tokens.border,
		borderLeftColor: tokens.border,
		backgroundColor: tokens.colorInput,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingTop: "calc(0.25rem * 2.5)",
		paddingBottom: "calc(0.25rem * 2.5)",
		fontFamily: constants.fontMono,
		fontSize: constants.fsSm,
		lineHeight: 1.6,
		color: tokens.fg65,
	},
	toolLabel: {
		flexShrink: 0,
		fontSize: constants.fsBase,
		fontWeight: 400,
		lineHeight: "calc(0.25rem * 5)",
	},
	fileTone: {
		color: tokens.colorFileNode,
	},
	commandTone: {
		color: tokens.colorCommandNode,
	},
	sessionTone: {
		color: tokens.colorSessionNode,
	},
	skillTone: {
		color: tokens.colorSkillNode,
	},
	chevronOpen: {},
	lucideScale: {
		display: "block",
		verticalAlign: "middle",
		scale: constants.iconScale,
		transformOrigin: "center",
	},
});
