import * as stylex from "@stylexjs/stylex";
import { colors, constants, lengths, times } from "./public-tokens.stylex";

const mobile = "@media (max-width: 900px)";
const mobileNavHeight = `max(${lengths.navHeight}, calc(env(safe-area-inset-top, 0px) + 44px))`;
const canHover = "@media (hover: hover)";
const pageInlinePadding = `max(24px, calc(50vw - ${lengths.pageWidth} / 2))`;
const pageWidth = `min(${lengths.pageWidth}, calc(100% - ${lengths.pageGutter}))`;

export const headerStyles = stylex.create({
	nav: {
		position: { default: "sticky", [mobile]: "sticky" },
		zIndex: 30,
		top: 0,
		isolation: "isolate",
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		minHeight: lengths.navHeight,
		columnGap: "16px",
		paddingInlineStart: pageInlinePadding,
		paddingInlineEnd: pageInlinePadding,
		paddingTop: "env(safe-area-inset-top, 0px)",
		borderBottomWidth: 0,
		backgroundColor: "transparent",
	},
	navOpen: {
		position: { default: "sticky", [mobile]: "fixed" },
		right: { default: null, [mobile]: 0 },
		left: { default: null, [mobile]: 0 },
		backgroundColor: { default: "transparent", [mobile]: colors.background },
	},
	navBackdrop: {
		content: "",
		position: "absolute",
		zIndex: 0,
		top: 0,
		right: 0,
		left: 0,
		height: "100%",
		pointerEvents: "none",
		backgroundColor: colors.navSurface,
		backdropFilter: "blur(12px)",
		display: { default: "block", [mobile]: "block" },
	},
	navBackdropOpen: { display: { default: "block", [mobile]: "none" } },
	navBackdropProducts: { height: "calc(100% + 188px)" },
	navBackdropResources: { height: "calc(100% + 188px)" },
	primary: {
		position: "relative",
		zIndex: 2,
		display: "flex",
		minWidth: 0,
		alignItems: "center",
		columnGap: "16px",
	},
	brand: {
		position: "relative",
		zIndex: 2,
		display: "flex",
		minWidth: 0,
		alignItems: "center",
		color: colors.foreground,
		textDecoration: "none",
	},
	links: {
		position: "relative",
		zIndex: 2,
		display: {
			default: "flex",
			[mobile]: "none",
		},
		alignItems: "stretch",
		height: "72px",
		columnGap: {
			default: null,
			"@media (max-width: 620px)": 0,
		},
	},
	topLink: {
		position: "relative",
		isolation: "isolate",
		display: "inline-flex",
		minHeight: {
			default: "38px",
			"@media (max-width: 620px)": "44px",
		},
		alignItems: "center",
		justifyContent: "center",
		paddingTop: 0,
		paddingRight: {
			default: "14px",
			"@media (max-width: 620px)": "7px",
		},
		paddingBottom: 0,
		paddingLeft: {
			default: "14px",
			"@media (max-width: 620px)": "7px",
		},
		borderRadius: lengths.radiusControl,
		fontSize: "14px",
		fontWeight: 400,
		lineHeight: "20px",
		textDecoration: "none",
		backgroundColor: "transparent",
		transitionProperty: "color, background-color, border-color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
		color: {
			default: colors.quiet,
			":hover": {
				default: colors.quiet,
				[canHover]: colors.foreground,
			},
		},
	},
	triggerSurface: {
		position: "absolute",
		zIndex: -1,
		top: "50%",
		right: 0,
		left: 0,
		height: "38px",
		translate: "0 -50%",
		borderRadius: lengths.radiusControl,
		backgroundColor: {
			default: "transparent",
			[canHover]: {
				default: "transparent",
				[stylex.when.ancestor(":hover")]: colors.hover,
			},
		},
		transitionProperty: "background",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
	},
	actions: {
		position: "relative",
		zIndex: 2,
		display: { default: "flex", [mobile]: "none" },
		alignItems: "center",
		columnGap: "8px",
	},
	github: {
		display: "inline-flex",
		width: {
			default: "40px",
			"@media (max-width: 620px)": "44px",
		},
		height: "40px",
		alignItems: "center",
		justifyContent: "center",
		borderRadius: lengths.radiusControl,
		color: {
			default: colors.quiet,
			":hover": {
				default: colors.quiet,
				[canHover]: colors.foreground,
			},
		},
		textDecoration: "none",
		transitionProperty: "color, background-color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
		backgroundColor: {
			default: "transparent",
			":hover": {
				default: "transparent",
				[canHover]: colors.hover,
			},
		},
	},
	githubIcon: { width: "18px", height: "18px" },
	button: {
		display: "inline-flex",
		minHeight: "40px",
		alignItems: "center",
		justifyContent: "center",
		columnGap: "8px",
		paddingTop: 0,
		paddingRight: "16px",
		paddingBottom: 0,
		paddingLeft: "16px",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopColor: {
			default: colors.borderStrong,
			":hover": {
				default: colors.borderStrong,
				[canHover]: colors.borderStrongHover,
			},
		},
		borderRightColor: {
			default: colors.borderStrong,
			":hover": {
				default: colors.borderStrong,
				[canHover]: colors.borderStrongHover,
			},
		},
		borderBottomColor: {
			default: colors.borderStrong,
			":hover": {
				default: colors.borderStrong,
				[canHover]: colors.borderStrongHover,
			},
		},
		borderLeftColor: {
			default: colors.borderStrong,
			":hover": {
				default: colors.borderStrong,
				[canHover]: colors.borderStrongHover,
			},
		},
		borderRadius: lengths.radiusControl,
		color: colors.foreground,
		backgroundColor: {
			default: "transparent",
			":hover": { default: "transparent", [canHover]: colors.hover },
		},
		fontWeight: 500,
		textDecoration: "none",
		transitionProperty: "color, background-color, border-color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
	},
	menu: {
		position: "relative",
		display: "flex",
		alignItems: "stretch",
		height: "72px",
	},
	menuTrigger: {
		position: "relative",
		isolation: "isolate",
		display: "inline-flex",
		minHeight: "38px",
		alignItems: "center",
		justifyContent: "center",
		columnGap: "6px",
		paddingTop: 0,
		paddingRight: "14px",
		paddingBottom: 0,
		paddingLeft: "14px",
		borderWidth: 0,
		color: {
			default: colors.quiet,
			":hover": {
				default: colors.quiet,
				[canHover]: colors.foreground,
			},
		},
		fontFamily: constants.fontSans,
		fontSize: "14px",
		fontWeight: 400,
		lineHeight: "20px",
		cursor: "pointer",
		backgroundColor: "transparent",
		transitionProperty: "color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
	},
	menuTriggerOpen: { color: colors.foreground },
	chevron: {
		display: "block",
		transitionProperty: "rotate",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
	},
	chevronOpen: { rotate: "180deg" },
	mega: {
		position: "absolute",
		zIndex: 3,
		top: "100%",
		right: 0,
		left: 0,
		height: "188px",
		isolation: "isolate",
		backgroundColor: "transparent",
		display: { default: "block", [mobile]: "none" },
	},
	megaResources: { height: "188px" },
	megaInner: {
		position: "relative",
		zIndex: 1,
		width: pageWidth,
		marginInlineStart: "auto",
		marginInlineEnd: "auto",
		paddingTop: "12px",
		paddingRight: 0,
		paddingBottom: "32px",
		paddingLeft: 0,
	},
	megaGrid: (offset: number) => ({
		display: "grid",
		gridTemplateColumns: "repeat(2, minmax(0, max-content))",
		columnGap: "64px",
		paddingLeft: offset,
	}),
	megaSection: { minWidth: 0 },
	menuItems: {
		display: "grid",
		rowGap: 0,
		marginTop: 0,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		paddingTop: 0,
		paddingRight: 0,
		paddingBottom: 0,
		paddingLeft: 0,
		listStyleType: "none",
	},
	menuItem: {
		display: "flex",
		minHeight: "48px",
		alignItems: "center",
		marginInlineStart: "-12px",
		marginInlineEnd: "-12px",
		paddingTop: 0,
		paddingRight: "12px",
		paddingBottom: 0,
		paddingLeft: "12px",
		borderRadius: lengths.radiusControl,
		color: colors.foreground,
		fontFamily: constants.fontSans,
		fontSize: "19px",
		fontWeight: 425,
		lineHeight: "28px",
		textDecoration: "none",
		textAlign: "left",
		transitionProperty: "color, background-color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
		backgroundColor: {
			default: "transparent",
			":hover": { default: "transparent", [canHover]: colors.hover },
		},
	},
	spacer: {
		display: { default: "none", [mobile]: "block" },
		height: mobileNavHeight,
		flexShrink: 0,
	},
	toggle: {
		display: { default: "none", [mobile]: "inline-flex" },
		position: "relative",
		zIndex: 2,
		width: "44px",
		height: "44px",
		marginInlineStart: "-10px",
		marginInlineEnd: "-8px",
		alignItems: "center",
		justifyContent: "center",
		padding: 0,
		borderWidth: 0,
		borderRadius: lengths.radiusControl,
		color: colors.foreground,
		backgroundColor: "transparent",
	},
	sheet: {
		display: { default: "none", [mobile]: "block" },
		position: "fixed",
		top: mobileNavHeight,
		right: 0,
		bottom: 0,
		left: 0,
		width: "auto",
		height: "auto",
		maxWidth: "none",
		maxHeight: "none",
		zIndex: 1,
		paddingTop: "24px",
		paddingRight: "24px",
		paddingBottom: "calc(32px + env(safe-area-inset-bottom, 0px))",
		paddingLeft: "24px",
		overflowY: "auto",
		scrollbarWidth: "none",
		color: "inherit",
		backgroundColor: colors.background,
		visibility: "hidden",
		opacity: 0,
		pointerEvents: "none",
		borderWidth: 0,
		"::-webkit-scrollbar": { display: "none" },
	},
	sheetOpen: { visibility: "visible", opacity: 1, pointerEvents: "auto" },
	sheetNav: { display: "flex", flexDirection: "column" },
	sheetGroup: { display: "flex", flexDirection: "column" },
	sheetSummary: {
		display: "flex",
		minHeight: "44px",
		alignItems: "center",
		justifyContent: "space-between",
		paddingTop: "8px",
		paddingRight: "12px",
		paddingBottom: "8px",
		paddingLeft: "12px",
		borderRadius: lengths.radiusControl,
		color: colors.foreground,
		fontSize: "22px",
		fontWeight: 400,
		lineHeight: "28px",
		listStyleType: "none",
		cursor: "pointer",
		backgroundColor: {
			default: "transparent",
			":hover": { default: "transparent", [canHover]: colors.hover },
		},
	},
	sheetChevron: {
		flexShrink: 0,
		transitionProperty: "rotate",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
	},
	sheetItems: {
		display: "grid",
		rowGap: 0,
		marginTop: 0,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		paddingTop: "8px",
		paddingRight: 0,
		paddingBottom: "16px",
		paddingLeft: 0,
		listStyleType: "none",
	},
	sheetItem: {
		display: "flex",
		minHeight: "44px",
		alignItems: "center",
		paddingTop: 0,
		paddingRight: "12px",
		paddingBottom: 0,
		paddingLeft: "12px",
		borderRadius: lengths.radiusControl,
		color: {
			default: colors.dim,
			":hover": { default: colors.dim, [canHover]: colors.foreground },
		},
		fontSize: "18px",
		lineHeight: "28px",
		textDecoration: "none",
		transitionProperty: "color, background-color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
		backgroundColor: {
			default: "transparent",
			":hover": { default: "transparent", [canHover]: colors.hover },
		},
	},
	sheetLink: { color: colors.foreground, fontSize: "22px" },
	sheetActions: {
		display: "flex",
		flexDirection: "column",
		rowGap: "12px",
		marginTop: "32px",
	},
	sheetAction: { width: "100%", minHeight: "48px", justifyContent: "center" },
	textLink: {
		display: "inline-flex",
		alignItems: "center",
		columnGap: "4px",
		color: {
			default: colors.quiet,
			":hover": { default: colors.quiet, [canHover]: colors.foreground },
		},
		fontFamily: constants.fontSans,
		fontSize: "16px",
		fontWeight: 400,
		lineHeight: "24px",
		textDecoration: "none",
		transitionProperty: "color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
	},
});
