import * as stylex from "@stylexjs/stylex";
import { colors, constants, lengths, times } from "./public-tokens.stylex";

const pageWidth =
	`min(${lengths.pageWidth}, calc(100% - ${lengths.pageGutter}))`;

export const styles = stylex.create({
	sectionWidth: {
		width: pageWidth,
		marginLeft: "auto",
		marginRight: "auto",
	},
	pageBottom: {
		paddingBottom: 120,
	},
	productHero: {
		marginBottom: 120,
	},
	productArticle: {
		display: "grid",
		minHeight: {
			default: 720,
			"@media (max-width: 900px)": 0,
		},
		alignItems: "center",
		columnGap: {
			default: 120,
			"@media (max-width: 900px)": 48,
		},
		rowGap: {
			default: 120,
			"@media (max-width: 900px)": 48,
		},
		paddingTop: 80,
		paddingBottom: 80,
		gridTemplateColumns: {
			"@media (max-width: 900px)": "minmax(0, 1fr)",
		},
	},
	productArticleEven: {
		gridTemplateColumns: {
			default: "minmax(260px, .72fr) minmax(0, 1.28fr)",
			"@media (max-width: 900px)": "minmax(0, 1fr)",
		},
	},
	productArticleOdd: {
		gridTemplateColumns: {
			default: "minmax(0, 1.28fr) minmax(260px, .72fr)",
			"@media (max-width: 900px)": "minmax(0, 1fr)",
		},
	},
	productCopyOdd: {
		order: {
			default: 2,
			"@media (max-width: 900px)": 0,
		},
	},
	productMediaOdd: {
		order: {
			default: 1,
			"@media (max-width: 900px)": 0,
		},
	},
	productText: {
		maxWidth: 448,
		marginTop: 24,
		color: colors.fine,
		fontSize: 16,
		lineHeight: "24px",
	},
	docsSection: {
		marginTop: 80,
		scrollMarginTop: 112,
	},
	docsSectionHeading: {
		color: colors.foreground,
		fontSize: 24,
		fontWeight: 425,
		lineHeight: "32px",
		letterSpacing: 0,
	},
	docsSectionLead: {
		marginTop: 24,
	},
	marginTop16: {
		marginTop: 16,
	},
	marginTop32: {
		marginTop: 32,
	},
	docsList: {
		paddingLeft: 24,
		listStyleType: "disc",
	},
	docsListItem: {
		marginBottom: 8,
	},
	docsStrong: {
		color: colors.foreground,
		fontWeight: 500,
	},
	docsInlineCode: {
		overflowWrap: "anywhere",
	},
	docsCode: {
		display: "block",
		maxWidth: "100%",
		overflowX: "auto",
		marginTop: 32,
		marginRight: 0,
		marginBottom: 32,
		marginLeft: 0,
		paddingTop: 16,
		paddingRight: 20,
		paddingBottom: 16,
		paddingLeft: 20,
		borderTopWidth: 1,
		borderRightWidth: 1,
		borderBottomWidth: 1,
		borderLeftWidth: 1,
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopColor: colors.borderSoft,
		borderRightColor: colors.borderSoft,
		borderBottomColor: colors.borderSoft,
		borderLeftColor: colors.borderSoft,
		borderTopLeftRadius: lengths.radiusCompact,
		borderTopRightRadius: lengths.radiusCompact,
		borderBottomRightRadius: lengths.radiusCompact,
		borderBottomLeftRadius: lengths.radiusCompact,
		color: colors.fine,
		fontFamily: constants.fontMono,
		fontSize: 14,
		fontWeight: 400,
		lineHeight: "20px",
	},
	docsNotice: {
		paddingTop: 16,
		paddingRight: 16,
		paddingBottom: 16,
		paddingLeft: 16,
		borderTopWidth: 1,
		borderRightWidth: 1,
		borderBottomWidth: 1,
		borderLeftWidth: 1,
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopColor: colors.borderSoft,
		borderRightColor: colors.borderSoft,
		borderBottomColor: colors.borderSoft,
		borderLeftColor: colors.borderSoft,
		borderTopLeftRadius: lengths.radiusCompact,
		borderTopRightRadius: lengths.radiusCompact,
		borderBottomRightRadius: lengths.radiusCompact,
		borderBottomLeftRadius: lengths.radiusCompact,
	},
	downloadIntro: {
		minHeight: 0,
		paddingTop: {
			default: "calc(72px + clamp(140px, 18svh, 208px) + 24px)",
			"@media (max-width: 620px)": 100,
		},
	},
	downloadCta: {
		width: {
			default: "100%",
			"@media (min-width: 621px)": 340,
		},
	},
	downloadMeta: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "center",
		columnGap: 16,
		rowGap: 8,
		marginTop: 16,
		color: colors.fine,
		fontFamily: constants.fontSans,
		fontSize: 14,
		fontWeight: 400,
		lineHeight: "20px",
	},
	button: {
		display: "inline-flex",
		minHeight: 40,
		alignItems: "center",
		justifyContent: "center",
		columnGap: 8,
		paddingRight: 16,
		paddingLeft: 16,
		borderTopWidth: 1,
		borderRightWidth: 1,
		borderBottomWidth: 1,
		borderLeftWidth: 1,
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopColor: {
			default: colors.foreground,
			"@media (hover: hover)": {
				":hover": colors.foregroundHover,
			},
		},
		borderRightColor: {
			default: colors.foreground,
			"@media (hover: hover)": {
				":hover": colors.foregroundHover,
			},
		},
		borderBottomColor: {
			default: colors.foreground,
			"@media (hover: hover)": {
				":hover": colors.foregroundHover,
			},
		},
		borderLeftColor: {
			default: colors.foreground,
			"@media (hover: hover)": {
				":hover": colors.foregroundHover,
			},
		},
		borderTopLeftRadius: lengths.radiusControl,
		borderTopRightRadius: lengths.radiusControl,
		borderBottomRightRadius: lengths.radiusControl,
		borderBottomLeftRadius: lengths.radiusControl,
		color: colors.buttonInk,
		backgroundColor: {
			default: colors.foreground,
			"@media (hover: hover)": {
				":hover": colors.foregroundHover,
			},
		},
		boxShadow: {
			default: `0 10px 30px ${colors.shadowControl}, 0 2px 10px ${colors.shadowControlDirect}`,
			"@media (hover: hover)": {
				default: `0 10px 30px ${colors.shadowControl}, 0 2px 10px ${colors.shadowControlDirect}`,
				":hover": `0 12px 34px ${colors.shadowControl}, 0 3px 14px ${colors.focusHalo}`,
			},
		},
		fontWeight: 500,
		textDecoration: "none",
		transitionProperty: "color, background, border-color, box-shadow",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
		width: {
			"@media (max-width: 620px)": "auto",
		},
	},
	notFoundRoutes: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "center",
		marginTop: 32,
	},
	notFoundRoute: {
		display: "flex",
		alignItems: "center",
		minHeight: {
			default: 32,
			"@media (max-width: 620px)": 44,
		},
		paddingTop: 4,
		paddingRight: 12,
		paddingBottom: 4,
		paddingLeft: 12,
		color: {
			default: colors.dim,
			"@media (hover: hover)": {
				":hover": colors.foreground,
			},
		},
		textDecoration: "none",
	},
	machine: {
		display: "grid",
		justifyContent: "start",
		width: pageWidth,
		marginLeft: "auto",
		marginRight: "auto",
		paddingTop: 88,
		paddingBottom: 120,
		color: colors.foreground,
		fontFamily: '"Geist Mono", ui-monospace, monospace',
		fontSize: 14,
		lineHeight: "22px",
		textAlign: "left",
	},
	machineInner: {
		gridColumnStart: "1",
		gridColumnEnd: "auto",
		width: "min(1080px, 100%)",
		maxWidth: "100%",
		minWidth: 0,
		justifySelf: "start",
	},
	machineTitle: {
		width: "max-content",
		maxWidth: "100%",
		marginTop: 32,
		color: colors.foreground,
		fontFamily: "inherit",
		fontSize: "inherit",
		fontWeight: "inherit",
		lineHeight: "inherit",
	},
	machineNote: {
		width: "max-content",
		maxWidth: "100%",
		marginTop: 8,
		color: colors.fine,
	},
	machineRoutes: {
		display: "flex",
		flexWrap: "wrap",
		columnGap: 24,
		rowGap: 8,
		marginTop: 24,
	},
	machineRoute: {
		color: colors.fine,
		textDecoration: "none",
	},
	machineSectionHeading: {
		marginTop: 48,
		color: colors.foreground,
		fontFamily: "inherit",
		fontSize: 14,
		fontWeight: "inherit",
		lineHeight: "inherit",
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
	},
	machineSectionPre: {
		marginTop: 16,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		color: colors.fine,
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
	},
	machineEnd: {
		marginTop: 64,
		color: colors.fine,
	},
	machineBanner: {
		display: "flex",
		width: "100%",
		flexDirection: "column",
		alignItems: "flex-start",
		marginTop: 0,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		paddingTop: 0,
		paddingRight: 0,
		paddingBottom: 0,
		paddingLeft: 0,
		borderTopWidth: 0,
		borderRightWidth: 0,
		borderBottomWidth: 0,
		borderLeftWidth: 0,
		backgroundColor: "transparent",
		color: colors.foreground,
		fontFamily: "inherit",
		fontSize: "clamp(6px, 1.4vw, 14px)",
		fontWeight: "inherit",
		lineHeight: 1.05,
		letterSpacing: 0,
		textAlign: "left",
		whiteSpace: "pre",
	},
	machineBannerPre: {
		maxWidth: "100%",
		marginTop: 0,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		fontFamily: "inherit",
		fontSize: "inherit",
		fontWeight: "inherit",
		lineHeight: "inherit",
		whiteSpace: "pre",
		overflowWrap: "normal",
		wordBreak: "normal",
	},
	overviewRows: {
		display: "grid",
		marginTop: 24,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		paddingTop: 0,
		paddingRight: 0,
		paddingBottom: 0,
		paddingLeft: 0,
		listStyleType: "none",
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: colors.border,
	},
	overviewRow: {
		display: "grid",
		gridTemplateColumns: {
			default: "minmax(0, 240px) minmax(0, 1fr)",
			"@media (max-width: 900px)": "minmax(0, 1fr)",
		},
		columnGap: {
			default: 32,
			"@media (max-width: 900px)": 0,
		},
		rowGap: {
			default: 0,
			"@media (max-width: 900px)": 6,
		},
		alignItems: "center",
		justifyItems: {
			"@media (max-width: 900px)": "start",
		},
		minHeight: {
			default: 56,
			"@media (max-width: 900px)": 0,
		},
		paddingTop: {
			default: 12,
			"@media (max-width: 900px)": 14,
		},
		paddingBottom: {
			default: 12,
			"@media (max-width: 900px)": 14,
		},
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
	},
	overviewLabel: {
		color: colors.foreground,
		fontFamily: constants.fontSans,
		fontSize: 16,
		fontWeight: 500,
		lineHeight: "24px",
	},
	overviewLabelCode: {
		fontFamily: constants.fontMono,
		fontWeight: 400,
		letterSpacing: 0,
		overflowWrap: "anywhere",
	},
	overviewLink: {
		display: "inline-flex",
		justifySelf: "start",
		alignItems: "center",
		columnGap: 6,
		color: {
			default: colors.dim,
			"@media (hover: hover)": {
				":hover": colors.foreground,
			},
		},
		textDecoration: "none",
	},
	overviewArrow: {
		flexShrink: 0,
		color: "currentColor",
		transitionProperty: "color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
	},
	overviewText: {
		marginTop: 0,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		color: colors.fine,
	},
	overviewTextLink: {
		color: {
			default: colors.foreground,
			"@media (hover: hover)": {
				":hover": colors.foreground,
			},
		},
		textDecoration: "none",
	},
});
