import * as stylex from "@stylexjs/stylex";
import { colors, constants, lengths, times } from "./public-tokens.stylex";

const pageWidth =
	`min(${lengths.pageWidth}, calc(100% - ${lengths.pageGutter}))`;

export const styles = stylex.create({
	sectionWidth: {
		width: pageWidth,
		marginLeft: "auto",
		marginRight: "auto",
	},
	pageBottom: {
		paddingBottom: { default: 120, "@media (max-width: 620px)": 96 },
	},
	productHero: {
		marginBottom: { default: 120, "@media (max-width: 620px)": 80 },
	},
	productArticle: {
		display: "grid",
		minHeight: {
			default: 720,
			"@media (max-width: 900px)": 0,
		},
		alignItems: "center",
		columnGap: {
			default: 120,
			"@media (max-width: 900px)": 48,
		},
		rowGap: {
			default: 120,
			"@media (max-width: 900px)": 48,
		},
		paddingTop: { default: 80, "@media (max-width: 620px)": 64 },
		paddingBottom: { default: 80, "@media (max-width: 620px)": 64 },
		gridTemplateColumns: {
			"@media (max-width: 900px)": "minmax(0, 1fr)",
		},
	},
	productArticleEven: {
		gridTemplateColumns: {
			default: "minmax(260px, .72fr) minmax(0, 1.28fr)",
			"@media (max-width: 900px)": "minmax(0, 1fr)",
		},
	},
	productArticleOdd: {
		gridTemplateColumns: {
			default: "minmax(0, 1.28fr) minmax(260px, .72fr)",
			"@media (max-width: 900px)": "minmax(0, 1fr)",
		},
	},
	productCopyOdd: {
		order: {
			default: 2,
			"@media (max-width: 900px)": 0,
		},
	},
	productMediaOdd: {
		order: {
			default: 1,
			"@media (max-width: 900px)": 0,
		},
	},
	productText: {
		maxWidth: 448,
		marginTop: 24,
		color: colors.fine,
		fontSize: 16,
		lineHeight: "24px",
	},
	docsSection: {
		marginTop: 80,
		scrollMarginTop: 112,
	},
	docsSectionHeading: {
		color: colors.foreground,
		fontSize: 24,
		fontWeight: 425,
		lineHeight: "32px",
		letterSpacing: 0,
	},
	docsSectionLead: {
		marginTop: 24,
	},
	marginTop16: {
		marginTop: 16,
	},
	marginTop32: {
		marginTop: 32,
	},
	docsList: {
		paddingLeft: 24,
		listStyleType: "disc",
	},
	docsListItem: {
		marginBottom: 8,
	},
	docsStrong: {
		color: colors.foreground,
		fontWeight: 500,
	},
	docsInlineCode: {
		overflowWrap: "anywhere",
	},
	docsCode: {
		display: "block",
		maxWidth: "100%",
		overflowX: "auto",
		marginTop: 32,
		marginRight: 0,
		marginBottom: 32,
		marginLeft: 0,
		paddingBlock: 16,
		paddingInline: 20,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: colors.borderSoft,
		borderRadius: lengths.radiusCompact,
		color: colors.fine,
		fontFamily: constants.fontMono,
		fontSize: 16,
		fontWeight: 400,
		lineHeight: "24px",
	},
	docsNotice: {
		padding: 16,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: colors.borderSoft,
		borderRadius: lengths.radiusCompact,
	},
	downloadIntro: {
		minHeight: 0,
		paddingTop: {
			default: "calc(72px + clamp(140px, 18svh, 208px) + 24px)",
			"@media (max-width: 620px)": 100,
		},
	},
	downloadCta: {
		width: {
			default: "100%",
			"@media (min-width: 621px)": 340,
		},
	},
	downloadMeta: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "center",
		columnGap: 16,
		rowGap: 8,
		marginTop: 16,
		color: colors.fine,
		fontFamily: constants.fontSans,
		fontSize: 16,
		fontWeight: 400,
		lineHeight: "24px",
	},
	button: {
		display: "inline-flex",
		minHeight: 40,
		alignItems: "center",
		justifyContent: "center",
		columnGap: 8,
		paddingInline: 16,
		borderWidth: 1,
		borderStyle: "solid",
		borderColor: colors.foreground,
		borderRadius: lengths.radiusControl,
		color: colors.buttonInk,
		backgroundColor: colors.foreground,
		boxShadow: {
			default: `0 6px 20px ${colors.shadowControl}, 0 1px 6px ${colors.shadowControlDirect}`,
			"@media (hover: hover)": {
				":hover": `0 8px 24px ${colors.shadowControl}, 0 2px 8px ${colors.focusHalo}`,
			},
		},
		fontWeight: 500,
		textDecoration: "none",
		transitionProperty: "color, background, border-color, box-shadow",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
		width: { "@media (max-width: 620px)": "auto" },
	},
	notFoundRoutes: {
		display: "flex",
		flexWrap: "wrap",
		justifyContent: "center",
		marginTop: 32,
	},
	notFoundRoute: {
		display: "flex",
		alignItems: "center",
		minHeight: {
			default: 32,
			"@media (max-width: 620px)": 44,
		},
		paddingTop: 4,
		paddingRight: 12,
		paddingBottom: 4,
		paddingLeft: 12,
		color: {
			default: colors.dim,
			"@media (hover: hover)": {
				":hover": colors.foreground,
			},
		},
		textDecoration: "none",
	},
	machine: {
		display: "grid",
		justifyContent: "start",
		width: pageWidth,
		marginLeft: "auto",
		marginRight: "auto",
		paddingTop: 88,
		paddingBottom: 120,
		color: colors.foreground,
		fontFamily: '"Geist Mono", ui-monospace, monospace',
		fontSize: 16,
		lineHeight: "24px",
		textAlign: "left",
	},
	machineInner: {
		gridColumnStart: "1",
		gridColumnEnd: "auto",
		width: "min(1080px, 100%)",
		maxWidth: "100%",
		minWidth: 0,
		justifySelf: "start",
	},
	machineTitle: {
		width: "max-content",
		maxWidth: "100%",
		marginTop: 32,
		color: colors.foreground,
		fontFamily: "inherit",
		fontSize: "inherit",
		fontWeight: "inherit",
		lineHeight: "inherit",
	},
	machineNote: {
		width: "max-content",
		maxWidth: "100%",
		marginTop: 8,
		color: colors.fine,
	},
	machineRoutes: {
		display: "flex",
		flexWrap: "wrap",
		columnGap: 24,
		rowGap: 8,
		marginTop: 24,
	},
	machineRoute: {
		display: "inline-flex",
		minWidth: { default: 0, "@media (max-width: 620px)": "44px" },
		minHeight: { default: "24px", "@media (max-width: 620px)": "44px" },
		alignItems: "center",
		color: colors.fine,
		textDecoration: "none",
	},
	machineSectionHeading: {
		marginTop: 48,
		color: colors.foreground,
		fontFamily: "inherit",
		fontSize: 16,
		fontWeight: "inherit",
		lineHeight: "inherit",
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
	},
	machineSectionPre: {
		marginTop: 16,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		color: colors.fine,
		whiteSpace: "pre-wrap",
		overflowWrap: "anywhere",
	},
	machineEnd: {
		marginTop: 64,
		color: colors.fine,
	},
	machineBanner: {
		display: { default: "flex", "@media (max-width: 620px)": "none" },
		width: "100%",
		flexDirection: "column",
		alignItems: "flex-start",
		margin: 0,
		padding: 0,
		borderWidth: 0,
		backgroundColor: "transparent",
		color: colors.foreground,
		fontFamily: "inherit",
		fontSize: "clamp(6px, 1.4vw, 16px)",
		fontWeight: "inherit",
		lineHeight: 1.05,
		letterSpacing: 0,
		textAlign: "left",
		whiteSpace: "pre",
	},
	machineBannerPre: {
		maxWidth: "100%",
		margin: 0,
		backgroundImage: `linear-gradient(color-mix(in srgb, ${colors.selectionSkyBright} 30%, ${colors.foreground}), color-mix(in srgb, ${colors.selectionSkyBlue} 25%, ${colors.foreground}), color-mix(in srgb, ${colors.selectionSkyNight} 20%, ${colors.foreground}))`,
		backgroundClip: "text",
		WebkitBackgroundClip: "text",
		WebkitTextFillColor: "transparent",
		color: "transparent",
		fontFamily: "inherit",
		fontSize: "inherit",
		fontWeight: "inherit",
		lineHeight: "inherit",
		whiteSpace: "pre",
		overflowWrap: "normal",
		wordBreak: "normal",
	},
	overviewRows: {
		display: "grid",
		marginTop: 24,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		paddingTop: 0,
		paddingRight: 0,
		paddingBottom: 0,
		paddingLeft: 0,
		listStyleType: "none",
		borderTopWidth: 1,
		borderTopStyle: "solid",
		borderTopColor: colors.border,
	},
	overviewRow: {
		display: "grid",
		gridTemplateColumns: {
			default: "minmax(0, 240px) minmax(0, 1fr)",
			"@media (max-width: 900px)": "minmax(0, 1fr)",
		},
		columnGap: {
			default: 32,
			"@media (max-width: 900px)": 0,
		},
		rowGap: {
			default: 0,
			"@media (max-width: 900px)": 6,
		},
		alignItems: "start",
		justifyItems: {
			"@media (max-width: 900px)": "start",
		},
		minHeight: {
			default: 56,
			"@media (max-width: 900px)": 0,
		},
		paddingTop: {
			default: 12,
			"@media (max-width: 900px)": 14,
		},
		paddingBottom: {
			default: 12,
			"@media (max-width: 900px)": 14,
		},
		borderBottomWidth: 1,
		borderBottomStyle: "solid",
		borderBottomColor: colors.border,
	},
	overviewLabel: {
		color: colors.foreground,
		fontFamily: constants.fontSans,
		fontSize: 16,
		fontWeight: 500,
		lineHeight: "24px",
	},
	overviewLabelCode: {
		fontFamily: constants.fontMono,
		fontWeight: 400,
		letterSpacing: 0,
		overflowWrap: "anywhere",
	},
	overviewLink: {
		display: "inline-flex",
		minWidth: { default: 0, "@media (max-width: 900px)": "44px" },
		minHeight: { default: "24px", "@media (max-width: 900px)": "44px" },
		justifySelf: "start",
		alignItems: "center",
		columnGap: 6,
		color: {
			default: colors.dim,
			"@media (hover: hover)": {
				":hover": colors.foreground,
			},
		},
		textDecoration: "none",
	},
	overviewArrow: {
		flexShrink: 0,
		color: "currentColor",
		transitionProperty: "color",
		transitionDuration: times.fast,
		transitionTimingFunction: "ease-out",
	},
	overviewText: {
		marginTop: 0,
		marginRight: 0,
		marginBottom: 0,
		marginLeft: 0,
		color: colors.fine,
	},
	overviewTextLink: {
		display: "inline-flex",
		minHeight: { default: "24px", "@media (max-width: 900px)": "44px" },
		alignItems: "center",
		color: {
			default: colors.foreground,
			"@media (hover: hover)": {
				":hover": colors.foreground,
			},
		},
		textDecoration: "none",
	},
});
