import * as stylex from "@stylexjs/stylex";
import { constants, depth, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
	div71: {
		display: "flex",
		minHeight: "0px",
		width: {
			default: "820px",
			"@media (width < 48rem)": "680px",
		},
	},
	section72: {
		display: "flex",
		minHeight: "0px",
		width: {
			default: "320px",
			"@media (width < 48rem)": "280px",
		},
		flexShrink: 0,
		flexDirection: "column",
		borderRightStyle: "solid",
		borderRightWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiBg,
		boxShadow: `1px 0 0 ${depth.hairline}, 6px 0 16px ${depth.far}`,
	},
	header73: {
		display: "flex",
		height: "calc(0.25rem * 14)",
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "space-between",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		paddingLeft: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
	},
	div74: {
		minWidth: "0px",
	},
	h175: {
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsXl,
		fontWeight: 500,
		color: tokens.uiFg,
	},
	p78: {
		fontSize: constants.fsXs,
		color: tokens.uiMuted,
	},
	button84: {
		lineHeight: 1.5,
		display: "inline-flex",
		height: "calc(0.25rem * 7)",
		alignItems: "center",
		rowGap: "0.25rem",
		columnGap: "0.25rem",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		backgroundColor: {
			default: tokens.uiFg,
			":hover": tokens.uiAccent,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		fontSize: constants.fsXs,
		color: tokens.uiBg,
	},
	plus86: {
		height: "calc(0.25rem * 3)",
		width: "calc(0.25rem * 3)",
	},
	div90: {
		display: "grid",
		rowGap: "8px",
		flexShrink: 0,
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiSeparator,
		borderRightColor: tokens.uiSeparator,
		borderBottomColor: tokens.uiSeparator,
		borderLeftColor: tokens.uiSeparator,
		paddingTop: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingBottom: "calc(0.25rem * 3)",
		paddingLeft: "calc(0.25rem * 3)",
	},
	label91: {
		position: "relative",
		display: "block",
	},
	span92: {
		position: "absolute",
		width: "1px",
		height: "1px",
		paddingTop: 0,
		paddingRight: 0,
		paddingBottom: 0,
		paddingLeft: 0,
		marginTop: "-1px",
		marginRight: "-1px",
		marginBottom: "-1px",
		marginLeft: "-1px",
		overflowX: "hidden",
		overflowY: "hidden",
		clipPath: "inset(50%)",
		whiteSpace: "nowrap",
		borderTopWidth: 0,
		borderRightWidth: 0,
		borderBottomWidth: 0,
		borderLeftWidth: 0,
	},
	search93: {
		position: "absolute",
		left: "calc(0.25rem * 3)",
		top: "calc(1 / 2 * 100%)",
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		translate: "0 -50%",
		color: tokens.uiMuted,
	},
	element98: {
		height: "calc(0.25rem * 8)",
		width: "100%",
		borderTopLeftRadius: constants.sidebarRowRadius,
		borderTopRightRadius: constants.sidebarRowRadius,
		borderBottomRightRadius: constants.sidebarRowRadius,
		borderBottomLeftRadius: constants.sidebarRowRadius,
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiSurface,
		boxShadow: constants.recessedElevation,
		paddingLeft: "calc(0.25rem * 9)",
		paddingRight: "calc(0.25rem * 3)",
		fontSize: constants.fsSm,
		outlineStyle: "none",
	},
	div101: {
		display: "inline-flex",
		borderTopLeftRadius: constants.sidebarRowRadius,
		borderTopRightRadius: constants.sidebarRowRadius,
		borderBottomRightRadius: constants.sidebarRowRadius,
		borderBottomLeftRadius: constants.sidebarRowRadius,
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiSurface,
		boxShadow: constants.panelElevation,
		paddingTop: "calc(0.25rem * 0.5)",
		paddingRight: "calc(0.25rem * 0.5)",
		paddingBottom: "calc(0.25rem * 0.5)",
		paddingLeft: "calc(0.25rem * 0.5)",
	},
	ul116: {
		display: { default: null, "::-webkit-scrollbar": "none" },
		scrollbarWidth: "none",
		minHeight: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
		borderBottomStyle: "solid",
		borderTopStyle: "solid",
		overflowY: "auto",
		paddingTop: "calc(0.25rem * 1.5)",
		paddingRight: "calc(0.25rem * 1.5)",
		paddingBottom: "calc(0.25rem * 1.5)",
		paddingLeft: "calc(0.25rem * 1.5)",
	},
	span126: {
		display: "flex",
		alignItems: "flex-start",
		rowGap: "calc(0.25rem * 3)",
		columnGap: "calc(0.25rem * 3)",
	},
	span130: {
		minWidth: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
	},
	span131: {
		display: "block",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsBase,
		fontWeight: 500,
	},
	span134: {
		marginTop: "0.25rem",
		display: "flex",
		alignItems: "center",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsSm,
		color: tokens.uiMuted,
	},
	clock135: {
		height: "calc(0.25rem * 3)",
		width: "calc(0.25rem * 3)",
		flexShrink: 0,
	},
	span138: {
		marginTop: "0.25rem",
		display: "block",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsXs,
		color: tokens.uiMuted75,
	},
	section152: {
		display: "flex",
		minHeight: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
		flexDirection: "column",
		backgroundColor: tokens.uiBg,
	},
	header153: {
		display: "flex",
		height: "calc(0.25rem * 14)",
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "space-between",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		paddingLeft: "calc(0.25rem * 5)",
		paddingRight: "calc(0.25rem * 5)",
	},
	h2155: {
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsLg,
		fontWeight: 500,
	},
	div162: {
		display: "flex",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
	},
	button165: {
		lineHeight: 1.5,
		display: "inline-flex",
		height: "calc(0.25rem * 7)",
		alignItems: "center",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		fontSize: constants.fsXs,
		backgroundColor: {
			default: "transparent",
			":hover": tokens.uiHover,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
	},
	button171: {
		lineHeight: 1.5,
		display: "inline-flex",
		height: "calc(0.25rem * 7)",
		alignItems: "center",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		backgroundColor: {
			default: tokens.uiFg,
			":hover": tokens.uiAccent,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		fontSize: constants.fsXs,
		color: tokens.uiBg,
	},
	div178: {
		display: { default: null, "::-webkit-scrollbar": "none" },
		scrollbarWidth: "none",
		minHeight: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
		overflowY: "auto",
		paddingLeft: "calc(0.25rem * 5)",
		paddingRight: "calc(0.25rem * 5)",
		paddingTop: "calc(0.25rem * 4)",
		paddingBottom: "calc(0.25rem * 4)",
	},
	div179: {
		display: "grid",
		rowGap: "calc(0.25rem * 4)",
		columnGap: "calc(0.25rem * 4)",
	},
	label180: {
		display: "grid",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
		fontSize: constants.fsXs,
		fontWeight: 500,
	},
	input185: {
		lineHeight: 1.5,
		height: "calc(0.25rem * 8)",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiSurface,
		boxShadow: constants.recessedElevation,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		fontSize: constants.fsSm,
		fontWeight: 400,
	},
	textarea194: {
		resize: "none",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiSurface,
		boxShadow: constants.recessedElevation,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingTop: "calc(0.25rem * 2)",
		paddingBottom: "calc(0.25rem * 2)",
		fontSize: constants.fsSm,
		fontWeight: 400,
		lineHeight: "calc(0.25rem * 5)",
	},
	span196: {
		fontWeight: 400,
		color: tokens.uiMuted,
	},
	section201: {
		borderTopStyle: "solid",
		borderTopWidth: "1px",
		borderTopColor: tokens.uiSeparator,
		borderRightColor: tokens.uiSeparator,
		borderBottomColor: tokens.uiSeparator,
		borderLeftColor: tokens.uiSeparator,
		paddingTop: "calc(0.25rem * 4)",
	},
	div202: {
		display: "flex",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
	},
	clock203: {
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		color: tokens.uiMuted,
	},
	h3205: {
		fontSize: constants.fsSm,
		fontWeight: 500,
	},
	div213: {
		marginTop: "calc(0.25rem * 3)",
		display: "flex",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
	},
	span214: {
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiActive,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingTop: "calc(0.25rem * 1.5)",
		paddingBottom: "calc(0.25rem * 1.5)",
		fontSize: constants.fsXs,
	},
	span217: {
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingTop: "calc(0.25rem * 1.5)",
		paddingBottom: "calc(0.25rem * 1.5)",
		fontSize: constants.fsXs,
	},
	div225: {
		display: "grid",
		gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
		rowGap: "calc(0.25rem * 4)",
		columnGap: "calc(0.25rem * 4)",
		borderTopStyle: "solid",
		borderTopWidth: "1px",
		borderTopColor: tokens.uiSeparator,
		borderRightColor: tokens.uiSeparator,
		borderBottomColor: tokens.uiSeparator,
		borderLeftColor: tokens.uiSeparator,
		paddingTop: "calc(0.25rem * 4)",
		fontSize: constants.fsXs,
	},
	p227: {
		fontWeight: 500,
	},
	p228: {
		marginTop: "calc(0.25rem * 1.5)",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiSurface,
		boxShadow: constants.recessedElevation,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingTop: "calc(0.25rem * 2)",
		paddingBottom: "calc(0.25rem * 2)",
		fontSize: constants.fsSm,
	},
	p234: {
		marginTop: "calc(0.25rem * 1.5)",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiSurface,
		boxShadow: constants.recessedElevation,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingTop: "calc(0.25rem * 2)",
		paddingBottom: "calc(0.25rem * 2)",
		fontFamily: constants.fontMono,
	},
	section239: {
		borderTopStyle: "solid",
		borderTopWidth: "1px",
		borderTopColor: tokens.uiSeparator,
		borderRightColor: tokens.uiSeparator,
		borderBottomColor: tokens.uiSeparator,
		borderLeftColor: tokens.uiSeparator,
		paddingTop: "calc(0.25rem * 4)",
		display: {
			default: null,
			"@media (width < 48rem)": "none",
		},
	},
	div243: {
		marginTop: "calc(0.25rem * 2)",
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingTop: "calc(0.25rem * 2)",
		paddingBottom: "calc(0.25rem * 2)",
		fontSize: constants.fsXs,
	},
	check245: {
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		color: tokens.uiAccent,
	},
	strong247: {
		display: "block",
		fontWeight: 500,
	},
	span248: {
		color: tokens.uiMuted,
	},
	span253: {
		fontFamily: constants.fontMono,
		color: tokens.uiMuted,
	},
	filter: {
		lineHeight: 1.5,
		height: "calc(0.25rem * 7)",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		fontSize: constants.fsXs,
	},
	filterActive: {
		backgroundColor: tokens.uiActive,
		color: tokens.uiFg,
	},
	filterIdle: {
		color: tokens.uiMuted,
		backgroundColor: {
			default: "transparent",
			":hover": tokens.uiHover,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
	},
	automationRow: {
		fontSize: constants.fsSm,
		lineHeight: 1.5,
		width: "100%",
		borderTopLeftRadius: constants.sidebarRowRadius,
		borderTopRightRadius: constants.sidebarRowRadius,
		borderBottomRightRadius: constants.sidebarRowRadius,
		borderBottomLeftRadius: constants.sidebarRowRadius,
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingTop: "calc(0.25rem * 2.5)",
		paddingBottom: "calc(0.25rem * 2.5)",
		textAlign: "left",
	},
	automationActive: {
		backgroundColor: tokens.uiActive,
	},
	automationIdle: {
		backgroundColor: {
			default: "transparent",
			":hover": tokens.hover60,
		},
	},
	statusDot: {
		marginTop: "calc(0.25rem * 1.5)",
		height: "calc(0.25rem * 1.5)",
		width: "calc(0.25rem * 1.5)",
		flexShrink: 0,
		borderTopLeftRadius: "calc(infinity * 1px)",
		borderTopRightRadius: "calc(infinity * 1px)",
		borderBottomRightRadius: "calc(infinity * 1px)",
		borderBottomLeftRadius: "calc(infinity * 1px)",
	},
	statusDotActive: {
		backgroundColor: tokens.uiAccent,
	},
	statusDotIdle: {
		backgroundColor: tokens.uiMuted45,
	},
	lucideScale: {
		display: "block",
		verticalAlign: "middle",
		scale: constants.iconScale,
		transformOrigin: "center",
	},
	automationDivider: {
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderBottomColor: tokens.separator70,
	},
});
