import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
	div25: {
		minHeight: "0px",
		width: {
			default: "820px",
			"@media (width < 48rem)": "680px",
		},
		overflowX: "hidden",
		overflowY: "hidden",
		paddingLeft: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 5)",
		},
		paddingRight: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 5)",
		},
		paddingTop: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 5)",
		},
		paddingBottom: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 5)",
		},
	},
	h327: {
		fontSize: constants.fs2xl,
		fontWeight: 500,
	},
	nav29: {
		marginTop: "calc(0.25rem * 5)",
		display: "flex",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiSeparator,
		borderRightColor: tokens.uiSeparator,
		borderBottomColor: tokens.uiSeparator,
		borderLeftColor: tokens.uiSeparator,
	},
	button35: {
		lineHeight: 1.5,
		display: "flex",
		height: "calc(0.25rem * 9)",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiFg,
		borderRightColor: tokens.uiFg,
		borderBottomColor: tokens.uiFg,
		borderLeftColor: tokens.uiFg,
		paddingLeft: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
		fontSize: constants.fsSm,
		backgroundColor: {
			default: "transparent",
			":hover": tokens.uiHover,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
	},
	monitor37: {
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
	},
	button41: {
		lineHeight: 1.5,
		display: "flex",
		height: "calc(0.25rem * 9)",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: "transparent",
		borderRightColor: "transparent",
		borderBottomColor: "transparent",
		borderLeftColor: "transparent",
		paddingLeft: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
		fontSize: constants.fsSm,
		color: tokens.uiMuted,
		backgroundColor: {
			default: "transparent",
			":hover": tokens.uiHover,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
	},
	section48: {
		marginTop: "calc(0.25rem * 6)",
		overflowX: "hidden",
		overflowY: "hidden",
		borderTopLeftRadius: "0.5rem",
		borderTopRightRadius: "0.5rem",
		borderBottomRightRadius: "0.5rem",
		borderBottomLeftRadius: "0.5rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiSurface,
		boxShadow: constants.panelElevation,
	},
	header49: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		rowGap: "calc(0.25rem * 4)",
		columnGap: "calc(0.25rem * 4)",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		paddingLeft: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
		paddingTop: "calc(0.25rem * 3)",
		paddingBottom: "calc(0.25rem * 3)",
	},
	h451: {
		fontSize: constants.fsMd,
		fontWeight: 500,
	},
	p54: {
		marginTop: "calc(0.25rem * 0.5)",
		fontSize: constants.fsXs,
		color: tokens.uiMuted,
	},
	div59: {
		display: "flex",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
	},
	span60: {
		borderTopLeftRadius: "calc(infinity * 1px)",
		borderTopRightRadius: "calc(infinity * 1px)",
		borderBottomRightRadius: "calc(infinity * 1px)",
		borderBottomLeftRadius: "calc(infinity * 1px)",
		backgroundColor: tokens.uiAccent12,
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		paddingTop: "0.25rem",
		paddingBottom: "0.25rem",
		fontSize: constants.fsXs,
		color: tokens.uiAccent,
	},
	button65: {
		lineHeight: 1.5,
		display: "inline-flex",
		height: "calc(0.25rem * 7)",
		alignItems: "center",
		rowGap: "0.25rem",
		columnGap: "0.25rem",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		backgroundColor: {
			default: tokens.uiFg,
			":hover": tokens.uiAccent,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		fontSize: constants.fsXs,
		color: tokens.uiBg,
	},
	plus67: {
		height: "calc(0.25rem * 3)",
		width: "calc(0.25rem * 3)",
	},
	div72: {
		borderBottomStyle: "solid",
		borderTopStyle: "solid",
	},
	button77: {
		fontSize: constants.fsSm,
		lineHeight: 1.5,
		display: "grid",
		width: "100%",
		gridTemplateColumns: "minmax(0,1.1fr) minmax(0,1fr) auto",
		alignItems: "center",
		rowGap: "calc(0.25rem * 4)",
		columnGap: "calc(0.25rem * 4)",
		paddingLeft: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
		paddingTop: "calc(0.25rem * 3)",
		paddingBottom: "calc(0.25rem * 3)",
		textAlign: "left",
		backgroundColor: {
			default: "transparent",
			":hover": tokens.uiHover,
		},
	},
	span79: {
		display: "flex",
		minWidth: "0px",
		alignItems: "center",
		rowGap: "calc(0.25rem * 3)",
		columnGap: "calc(0.25rem * 3)",
	},
	span80: {
		display: "flex",
		height: "calc(0.25rem * 8)",
		width: "calc(0.25rem * 8)",
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiActive,
	},
	monitor82: {
		height: "calc(0.25rem * 4)",
		width: "calc(0.25rem * 4)",
	},
	span87: {
		minWidth: "0px",
	},
	strong88: {
		display: "block",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsSm,
		fontWeight: 500,
	},
	span91: {
		marginTop: "calc(0.25rem * 0.5)",
		display: "block",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsXs,
		color: tokens.uiMuted,
	},
	strong97: {
		display: "block",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontFamily: constants.fontMono,
		fontSize: constants.fsXs,
		fontWeight: 400,
	},
	span100: {
		marginTop: "calc(0.25rem * 0.5)",
		display: "block",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontFamily: constants.fontMono,
		fontSize: constants.fs2xs,
		color: tokens.uiMuted,
	},
	squarepen110: {
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		color: tokens.uiMuted,
	},
	section117: {
		marginTop: "calc(0.25rem * 5)",
		overflowX: "hidden",
		overflowY: "hidden",
		borderTopLeftRadius: "0.5rem",
		borderTopRightRadius: "0.5rem",
		borderBottomRightRadius: "0.5rem",
		borderBottomLeftRadius: "0.5rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiSurface,
		boxShadow: constants.panelElevation,
	},
	header118: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		paddingLeft: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
		paddingTop: "calc(0.25rem * 3)",
		paddingBottom: "calc(0.25rem * 3)",
	},
	div131: {
		display: "grid",
		gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
		borderLeftStyle: "solid",
		borderRightStyle: "solid",
	},
	div132: {
		paddingLeft: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
		paddingTop: "calc(0.25rem * 3)",
		paddingBottom: "calc(0.25rem * 3)",
	},
	span133: {
		display: "flex",
		alignItems: "center",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
		fontSize: constants.fsXs,
		color: tokens.uiMuted,
	},
	strong136: {
		marginTop: "0.25rem",
		display: "block",
		fontSize: constants.fsMd,
		fontWeight: 500,
	},
	span141: {
		fontSize: constants.fsXs,
		color: tokens.uiMuted,
	},
	strong144: {
		marginTop: "0.25rem",
		display: "block",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontFamily: constants.fontMono,
		fontSize: constants.fsXs,
		fontWeight: 400,
	},
	strong152: {
		marginTop: "0.25rem",
		display: "block",
		fontSize: constants.fsSm,
		fontWeight: 500,
	},
	statusBadge: {
		borderTopLeftRadius: "calc(infinity * 1px)",
		borderTopRightRadius: "calc(infinity * 1px)",
		borderBottomRightRadius: "calc(infinity * 1px)",
		borderBottomLeftRadius: "calc(infinity * 1px)",
		paddingLeft: "calc(0.25rem * 2)",
		paddingRight: "calc(0.25rem * 2)",
		paddingTop: "0.25rem",
		paddingBottom: "0.25rem",
		fontSize: constants.fs2xs,
	},
	statusActive: {
		backgroundColor: tokens.uiAccent12,
		color: tokens.uiAccent,
	},
	statusIdle: {
		backgroundColor: tokens.uiActive,
		color: tokens.uiMuted,
	},
	lucideScale: {
		display: "block",
		verticalAlign: "middle",
		scale: constants.iconScale,
		transformOrigin: "center",
	},
	rowDivider: {
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderBottomColor: tokens.uiSeparator,
	},
	columnDivider: {
		borderLeftStyle: "solid",
		borderLeftWidth: "1px",
		borderLeftColor: tokens.uiSeparator,
	},
});
