import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
	div74: {
		minHeight: "0px",
		width: {
			default: "820px",
			"@media (width < 48rem)": "680px",
		},
		overflowX: "hidden",
		overflowY: "hidden",
		paddingLeft: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 5)",
		},
		paddingRight: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 5)",
		},
		paddingTop: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 5)",
		},
		paddingBottom: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 5)",
		},
	},
	h376: {
		fontSize: constants.fs2xl,
		fontWeight: 500,
	},
	p77: {
		marginTop: "0.25rem",
		fontSize: constants.fsSm,
		color: tokens.uiMuted,
	},
	nav84: {
		marginTop: "calc(0.25rem * 5)",
		display: "flex",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiSeparator,
		borderRightColor: tokens.uiSeparator,
		borderBottomColor: tokens.uiSeparator,
		borderLeftColor: tokens.uiSeparator,
	},
	icon94: {
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
	},
	div100: {
		marginTop: "calc(0.25rem * 5)",
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.uiSeparator,
		borderRightColor: tokens.uiSeparator,
		borderBottomColor: tokens.uiSeparator,
		borderLeftColor: tokens.uiSeparator,
		paddingBottom: "calc(0.25rem * 3)",
	},
	span102: {
		fontSize: constants.fsMd,
		fontWeight: 500,
	},
	span105: {
		marginLeft: "calc(0.25rem * 2)",
		fontSize: constants.fsSm,
		color: tokens.uiMuted,
	},
	span109: {
		borderTopLeftRadius: "calc(infinity * 1px)",
		borderTopRightRadius: "calc(infinity * 1px)",
		borderBottomRightRadius: "calc(infinity * 1px)",
		borderBottomLeftRadius: "calc(infinity * 1px)",
		backgroundColor: tokens.uiAccent12,
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		paddingTop: "0.25rem",
		paddingBottom: "0.25rem",
		fontSize: constants.fsXs,
		color: tokens.uiAccent,
	},
	section114: {
		marginTop: "calc(0.25rem * 5)",
	},
	div115: {
		display: "flex",
		alignItems: "flex-end",
		justifyContent: "space-between",
		rowGap: "calc(0.25rem * 4)",
		columnGap: "calc(0.25rem * 4)",
	},
	h4117: {
		fontSize: constants.fsLg,
		fontWeight: 500,
	},
	p120: {
		marginTop: "calc(0.25rem * 0.5)",
		fontSize: constants.fsXs,
		color: tokens.uiMuted,
	},
	button126: {
		lineHeight: 1.5,
		display: "inline-flex",
		height: "calc(0.25rem * 7)",
		alignItems: "center",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		fontSize: constants.fsXs,
		backgroundColor: {
			default: "transparent",
			":hover": tokens.uiHover,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
	},
	search128: {
		height: "calc(0.25rem * 3)",
		width: "calc(0.25rem * 3)",
	},
	div132: {
		marginTop: "calc(0.25rem * 3)",
		display: "grid",
		gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
		rowGap: "calc(0.25rem * 3)",
		columnGap: "calc(0.25rem * 3)",
	},
	element141: {
		fontSize: constants.fsSm,
		lineHeight: 1.5,
		color: tokens.fg80,
		opacity: "100%",
		position: "relative",
		minHeight: "calc(0.25rem * 44)",
		overflowX: "hidden",
		overflowY: "hidden",
		borderTopLeftRadius: "0.75rem",
		borderTopRightRadius: "0.75rem",
		borderBottomRightRadius: "0.75rem",
		borderBottomLeftRadius: "0.75rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: {
			default: tokens.uiSurface,
			":hover": tokens.uiHover,
		},
		paddingTop: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
		paddingBottom: "calc(0.25rem * 4)",
		paddingLeft: "calc(0.25rem * 4)",
		textAlign: "left",
	},
	span143: {
		position: "absolute",
		top: "0px",
		bottom: "0px",
		left: "0px",
		width: "calc(0.25rem * 0.5)",
		backgroundColor: tokens.uiAccent,
		opacity: "80%",
	},
	span144: {
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "space-between",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
	},
	span145: {
		display: "flex",
		minWidth: "0px",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2.5)",
		columnGap: "calc(0.25rem * 2.5)",
	},
	span146: {
		display: "flex",
		height: "calc(0.25rem * 8)",
		width: "calc(0.25rem * 8)",
		flexShrink: 0,
		alignItems: "center",
		justifyContent: "center",
		borderTopLeftRadius: "0.5rem",
		borderTopRightRadius: "0.5rem",
		borderBottomRightRadius: "0.5rem",
		borderBottomLeftRadius: "0.5rem",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.uiBorder,
		borderRightColor: tokens.uiBorder,
		borderBottomColor: tokens.uiBorder,
		borderLeftColor: tokens.uiBorder,
		backgroundColor: tokens.uiActive,
		fontSize: constants.fsXs,
		fontWeight: 600,
	},
	span149: {
		minWidth: "0px",
	},
	span150: {
		display: "block",
		fontSize: constants.fs2xs,
		fontWeight: 500,
		textTransform: "uppercase",
		letterSpacing: "0.12em",
		color: tokens.uiMuted,
	},
	strong153: {
		marginTop: "calc(0.25rem * 0.5)",
		display: "block",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsBase,
		fontWeight: 500,
	},
	chevronright158: {
		marginTop: "0.25rem",
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		flexShrink: 0,
		color: tokens.uiMuted,
	},
	span160: {
		marginTop: "calc(0.25rem * 3)",
		overflowX: "hidden",
		overflowY: "hidden",
		display: "block",
		WebkitBoxOrient: "vertical",
		WebkitLineClamp: 2,
		fontSize: constants.fsXs,
		lineHeight: "calc(0.25rem * 4)",
		color: tokens.uiMuted,
	},
	span163: {
		marginTop: "calc(0.25rem * 4)",
		display: "flex",
		flexWrap: "wrap",
		alignItems: "center",
		columnGap: "calc(0.25rem * 2)",
		rowGap: "0.25rem",
		fontFamily: constants.fontMono,
		fontSize: constants.fs2xs,
		color: tokens.uiMuted,
	},
	span168: {
		marginLeft: "auto",
		display: "inline-flex",
		alignItems: "center",
		rowGap: "0.25rem",
		columnGap: "0.25rem",
		fontFamily: constants.fontSans,
		fontWeight: 500,
	},
	span182: {
		marginTop: "calc(0.25rem * 3)",
		display: "inline-flex",
		height: "calc(0.25rem * 7)",
		alignItems: "center",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
		borderTopLeftRadius: "0.375rem",
		borderTopRightRadius: "0.375rem",
		borderBottomRightRadius: "0.375rem",
		borderBottomLeftRadius: "0.375rem",
		backgroundColor: tokens.uiFg,
		paddingLeft: "calc(0.25rem * 2.5)",
		paddingRight: "calc(0.25rem * 2.5)",
		fontSize: constants.fsXs,
		color: tokens.uiBg,
	},
	tab: {
		lineHeight: 1.5,
		display: "flex",
		height: "calc(0.25rem * 9)",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		paddingLeft: "calc(0.25rem * 4)",
		paddingRight: "calc(0.25rem * 4)",
		fontSize: constants.fsXs,
		backgroundColor: {
			default: "transparent",
			":hover": tokens.uiHover,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
	},
	tabActive: {
		borderTopColor: tokens.uiFg,
		borderRightColor: tokens.uiFg,
		borderBottomColor: tokens.uiFg,
		borderLeftColor: tokens.uiFg,
		color: tokens.uiFg,
	},
	tabIdle: {
		borderTopColor: "transparent",
		borderRightColor: "transparent",
		borderBottomColor: "transparent",
		borderLeftColor: "transparent",
		color: tokens.uiMuted,
	},
	lucideScale: {
		display: "block",
		verticalAlign: "middle",
		scale: constants.iconScale,
		transformOrigin: "center",
	},
});
