import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
	div24: {
		minHeight: "0px",
		width: {
			default: "820px",
			"@media (width < 48rem)": "680px",
		},
		overflowX: "hidden",
		overflowY: "hidden",
		paddingLeft: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 4)",
		},
		paddingRight: {
			default: "calc(0.25rem * 6)",
			"@media (width < 48rem)": "calc(0.25rem * 4)",
		},
		paddingTop: {
			default: "calc(0.25rem * 5)",
			"@media (width < 48rem)": "calc(0.25rem * 4)",
		},
		paddingBottom: {
			default: "calc(0.25rem * 5)",
			"@media (width < 48rem)": "calc(0.25rem * 4)",
		},
	},
	header25: {
		display: "flex",
		alignItems: "flex-start",
		justifyContent: "space-between",
		rowGap: "calc(0.25rem * 4)",
		columnGap: "calc(0.25rem * 4)",
	},
	div26: {
		minWidth: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
	},
	div27: {
		display: "flex",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
		fontSize: constants.fsSm,
	},
	span28: {
		display: "inline-flex",
		height: "calc(0.25rem * 1.5)",
		width: "calc(0.25rem * 1.5)",
		borderTopLeftRadius: "calc(infinity * 1px)",
		borderTopRightRadius: "calc(infinity * 1px)",
		borderBottomRightRadius: "calc(infinity * 1px)",
		borderBottomLeftRadius: "calc(infinity * 1px)",
		backgroundColor: tokens.uiAccent,
	},
	span29: {
		fontWeight: 500,
		color: tokens.uiAccent,
	},
	h331: {
		marginTop: "calc(0.25rem * 1.5)",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fs3xl,
		fontWeight: 600,
		lineHeight: 1.25,
		letterSpacing: "-0.01em",
	},
	div35: {
		display: "flex",
		alignItems: "center",
		rowGap: "calc(0.25rem * 1.5)",
		columnGap: "calc(0.25rem * 1.5)",
	},
	button38: {
		lineHeight: 1.5,
		display: "inline-flex",
		height: "calc(0.25rem * 7)",
		alignItems: "center",
		columnGap: "calc(0.25rem * 1)",
		borderTopLeftRadius: "calc(infinity * 1px)",
		borderTopRightRadius: "calc(infinity * 1px)",
		borderBottomRightRadius: "calc(infinity * 1px)",
		borderBottomLeftRadius: "calc(infinity * 1px)",
		backgroundColor: {
			default: tokens.fg05,
			":hover": tokens.fg10,
		},
		transitionProperty: "background-color",
		transitionDuration: "130ms",
		paddingLeft: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		fontSize: constants.fsSm,
	},
	modelChevron: {
		height: "calc(0.25rem * 3)",
		width: "calc(0.25rem * 3)",
		flexShrink: 0,
		strokeWidth: 2,
	},
	div53: {
		marginTop: "calc(0.25rem * 5)",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.separator,
		borderRightColor: tokens.separator,
		borderBottomColor: tokens.separator,
		borderLeftColor: tokens.separator,
		paddingBottom: "calc(0.25rem * 5)",
	},
	dl54: {
		display: "grid",
		gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
		columnGap: "calc(0.25rem * 6)",
		rowGap: "calc(0.25rem * 4)",
	},
	dl65: {
		marginTop: "calc(0.25rem * 4)",
		display: "grid",
		gridTemplateColumns: "repeat(6, minmax(0, 1fr))",
		columnGap: "calc(0.25rem * 6)",
		borderTopStyle: "solid",
		borderTopWidth: "1px",
		borderTopColor: tokens.separator55,
		borderRightColor: tokens.separator55,
		borderBottomColor: tokens.separator55,
		borderLeftColor: tokens.separator55,
		paddingTop: "calc(0.25rem * 4)",
	},
	div78: {
		marginTop: "calc(0.25rem * 6)",
		display: "grid",
		gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
		rowGap: "calc(0.25rem * 5)",
		columnGap: "calc(0.25rem * 5)",
		borderTopStyle: "solid",
		borderTopWidth: "1px",
		borderTopColor: tokens.separator,
		borderRightColor: tokens.separator,
		borderBottomColor: tokens.separator,
		borderLeftColor: tokens.separator,
		paddingTop: "calc(0.25rem * 4)",
	},
	section83: {
		marginTop: "calc(0.25rem * 5)",
		borderTopStyle: "solid",
		borderTopWidth: "1px",
		borderTopColor: tokens.separator,
		borderRightColor: tokens.separator,
		borderBottomColor: tokens.separator,
		borderLeftColor: tokens.separator,
		paddingLeft: "calc(0.25rem * 2)",
		paddingRight: "calc(0.25rem * 2)",
		paddingTop: "calc(0.25rem * 4)",
		paddingBottom: "calc(0.25rem * 4)",
	},
	div84: {
		display: "flex",
		alignItems: "center",
		rowGap: "calc(0.25rem * 4)",
		columnGap: "calc(0.25rem * 4)",
		fontSize: constants.fsSm,
	},
	span85: {
		fontWeight: 500,
		color: tokens.hl2,
	},
	span852: {
		fontFamily: constants.fontMono,
		fontSize: constants.fsXs,
		color: tokens.dim65,
	},
	span86: {
		height: "3px",
		minWidth: "calc(0.25rem * 20)",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
		overflowX: "hidden",
		overflowY: "hidden",
		backgroundColor: tokens.dim15,
	},
	span862: {
		display: "block",
		height: "100%",
		width: "62%",
		backgroundColor: tokens.uiAccent,
	},
	span87: {
		fontFamily: constants.fontMono,
	},
	span88: {
		marginLeft: "auto",
		fontFamily: constants.fontMono,
		fontSize: constants.fsXs,
		color: tokens.dim,
	},
	section91: {
		borderTopStyle: "solid",
		borderTopWidth: "1px",
		borderTopColor: tokens.separator,
		borderRightColor: tokens.separator,
		borderBottomColor: tokens.separator,
		borderLeftColor: tokens.separator,
		paddingLeft: "calc(0.25rem * 2)",
		paddingRight: "calc(0.25rem * 2)",
		paddingTop: "calc(0.25rem * 4)",
	},
	div92: {
		display: "flex",
		alignItems: "center",
		justifyContent: "space-between",
		rowGap: "calc(0.25rem * 4)",
		columnGap: "calc(0.25rem * 4)",
	},
	h493: {
		fontSize: constants.fsSm,
		fontWeight: 500,
		color: tokens.hl2,
	},
	div96: {
		display: "flex",
		alignItems: "center",
		rowGap: "calc(0.25rem * 3)",
		columnGap: "calc(0.25rem * 3)",
		fontSize: constants.fsXs,
		color: tokens.dim,
	},
	span97: {
		borderTopLeftRadius: "calc(infinity * 1px)",
		borderTopRightRadius: "calc(infinity * 1px)",
		borderBottomRightRadius: "calc(infinity * 1px)",
		borderBottomLeftRadius: "calc(infinity * 1px)",
		backgroundColor: tokens.fg05,
		paddingLeft: "calc(0.25rem * 5)",
		paddingRight: "calc(0.25rem * 5)",
		paddingTop: "calc(0.25rem * 1.5)",
		paddingBottom: "calc(0.25rem * 1.5)",
		fontFamily: constants.fontMono,
	},
	span99: {
		color: tokens.accent,
	},
	div102: {
		marginTop: "calc(0.25rem * 3)",
		height: "calc(0.25rem * 24)",
		borderRadius: "8px",
		borderTopStyle: "solid",
		borderRightStyle: "solid",
		borderBottomStyle: "solid",
		borderLeftStyle: "solid",
		borderTopWidth: "1px",
		borderRightWidth: "1px",
		borderBottomWidth: "1px",
		borderLeftWidth: "1px",
		borderTopColor: tokens.separator,
		borderRightColor: tokens.separator,
		borderBottomColor: tokens.separator,
		borderLeftColor: tokens.separator,
		backgroundColor: tokens.uiBg,
		boxShadow: constants.recessedElevation,
		paddingTop: "calc(0.25rem * 3)",
		paddingRight: "calc(0.25rem * 3)",
		paddingBottom: "calc(0.25rem * 3)",
		paddingLeft: "calc(0.25rem * 3)",
		fontFamily: constants.fontMono,
		fontSize: constants.fsXs,
		lineHeight: "calc(0.25rem * 5)",
		color: tokens.dim,
	},
	span103: {
		color: tokens.uiAccent,
	},
	div127: {
		minWidth: "0px",
		overflowX: "hidden",
		overflowY: "hidden",
	},
	dt128: {
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsXs,
		color: tokens.dim,
	},
	span136: {
		fontSize: constants.fsXs,
		fontWeight: 400,
		color: tokens.dim,
	},
	dd142: {
		marginTop: "0.25rem",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsXs,
		color: tokens.dim75,
	},
	section152: {
		minWidth: "0px",
	},
	div153: {
		display: "flex",
		alignItems: "baseline",
		justifyContent: "space-between",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
	},
	span154: {
		fontSize: constants.fsXs,
		fontWeight: 400,
		color: tokens.dim50,
	},
	span155: {
		fontFamily: constants.fontMono,
		fontSize: constants.fsXs,
		color: tokens.dim,
	},
	div157: {
		position: "relative",
		marginTop: "calc(0.25rem * 2)",
		display: "grid",
		height: "calc(0.25rem * 24)",
		gridTemplateRows: "repeat(3, minmax(0, 1fr))",
		borderBottomStyle: "solid",
		borderBottomWidth: "1px",
		borderTopColor: tokens.fg75,
		borderRightColor: tokens.fg75,
		borderBottomColor: tokens.fg75,
		borderLeftColor: tokens.fg75,
	},
	span158: {
		borderTopStyle: "solid",
		borderTopWidth: "1px",
		borderTopColor: tokens.border40,
		borderRightColor: tokens.border40,
		borderBottomColor: tokens.border40,
		borderLeftColor: tokens.border40,
	},
	svg159: {
		position: "absolute",
		top: "0px",
		right: "0px",
		bottom: "0px",
		left: "0px",
		height: "100%",
		width: "100%",
		overflowX: "visible",
		overflowY: "visible",
		color: tokens.uiAccent,
	},
	p161: {
		marginTop: "0.25rem",
		fontSize: constants.fs2xs,
		color: tokens.dim55,
	},
	metric: {
		marginTop: "0.25rem",
		display: "flex",
		alignItems: "baseline",
		rowGap: "0.25rem",
		columnGap: "0.25rem",
		fontWeight: 600,
		lineHeight: 1,
	},
	metricQuiet: {
		fontSize: constants.fsLg,
	},
	metricLoud: {
		fontSize: constants.fs2xl,
	},
});
