import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
  button113: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "inline-flex",
    height: "100%",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    alignItems: "center",
    rowGap: "calc(0.25rem * 1.5)",
    columnGap: "calc(0.25rem * 1.5)",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
    paddingLeft: "calc(0.25rem * 2.5)",
    paddingRight: "calc(0.25rem * 2.5)",
    textAlign: "left",
  },
  icon116: {
    pointerEvents: "none",
    height: "calc(0.25rem * 3.5)",
    width: "calc(0.25rem * 3.5)",
    flexShrink: 0,
  },
  span118: {
    maxWidth: "8rem",
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: constants.fsSm,
  },
  span122: {
    fontSize: constants.fs2xs,
    color: tokens.dim70,
  },
  closeicon140: {
    display: "block",
    verticalAlign: "middle",
    pointerEvents: "none",
    height: "calc(0.25rem * 2)",
    width: "calc(0.25rem * 2)",
  },
  icon171: {
    pointerEvents: "none",
    height: "calc(0.25rem * 3.5)",
    width: "calc(0.25rem * 3.5)",
  },
  div205: {
    position: "relative",
    display: "flex",
    height: constants.paneToolbarHeight,
    flexShrink: 0,
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
    borderBottomStyle: "solid",
    borderBottomWidth: "1px",
    borderTopColor: tokens.border,
    borderRightColor: tokens.border,
    borderBottomColor: tokens.border,
    borderLeftColor: tokens.border,
    backgroundColor: tokens.colorHeader,
    boxShadow: constants.headerElevation,
    paddingLeft: "calc(0.25rem * 1.5)",
    paddingRight: "calc(0.25rem * 1.5)",
    fontSize: constants.fsSm,
  },
  div206: {
    display: {
      default: "flex",
      "::-webkit-scrollbar": "none",
    },
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    alignItems: "center",
    rowGap: "calc(0.25rem * 0.5)",
    columnGap: "calc(0.25rem * 0.5)",
    overflowX: "auto",
    overflowY: "hidden",
    paddingLeft: "calc(0.25rem * 0.5)",
    paddingRight: "calc(0.25rem * 0.5)",
    scrollbarWidth: "none",
  },
  div247: {
    marginLeft: "auto",
    display: "flex",
    flexShrink: 0,
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
  },
  section313: {
    display: { default: null, "::-webkit-scrollbar": "none" },
    scrollbarWidth: "none",
    minHeight: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflowY: "auto",
    backgroundColor: tokens.colorPanel,
    paddingLeft: "calc(0.25rem * 3)",
    paddingRight: "calc(0.25rem * 3)",
    paddingTop: "calc(0.25rem * 3)",
    paddingBottom: "calc(0.25rem * 3)",
  },
  div314: {
    display: "flex",
    flexDirection: "column",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
  },
  icon329: {
    height: "calc(0.25rem * 4)",
    width: "calc(0.25rem * 4)",
    flexShrink: 0,
    color: tokens.dim75,
  },
  span330: {
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  span331: {
    display: "block",
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: constants.fsLg,
    fontWeight: 500,
  },
  span334: {
    display: "block",
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: constants.fsSm,
    color: tokens.dim,
  },
  tab: {
    display: "inline-flex",
    height: "calc(0.25rem * 7)",
    minWidth: "0px",
    flexShrink: 0,
    alignItems: "center",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
    transitionProperty: "background-color,color",
    transitionDuration: "150ms",
  },
  selectedTab: {
    backgroundColor: tokens.colorSurfaceHover,
    color: tokens.fg,
  },
  idleTab: {
    color: {
      default: tokens.dim,
      ":hover": tokens.fg,
    },
  },
  closeButton: {
    marginLeft: "calc(0.25rem * -1)",
    marginRight: "0.25rem",
    display: "inline-flex",
    height: "calc(0.25rem * 5)",
    width: "calc(0.25rem * 5)",
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "0.25rem",
    borderTopRightRadius: "0.25rem",
    borderBottomRightRadius: "0.25rem",
    borderBottomLeftRadius: "0.25rem",
    color: {
      default: tokens.dim65,
      ":hover": tokens.fg,
    },
    opacity: {
      default: "0%",
      ":focus-visible": "100%",
    },
    transitionProperty: "color,opacity",
    transitionDuration: "150ms",
  },
  closeSelected: {
    opacity: "100%",
  },
  headerButton: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    position: "relative",
    zIndex: 10,
    display: "inline-flex",
    height: "calc(0.25rem * 7)",
    width: "calc(0.25rem * 7)",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
    transitionProperty: "background-color,color",
    transitionDuration: "150ms",
  },
  headerButtonActive: {
    backgroundColor: tokens.colorSurfaceHover,
    color: tokens.fg,
  },
  headerButtonIdle: {
    color: {
      default: tokens.dim,
      ":hover": tokens.fg,
    },
  },
  launcherCard: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "flex",
    minHeight: "0px",
    alignItems: "center",
    rowGap: "calc(0.25rem * 3)",
    columnGap: "calc(0.25rem * 3)",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
    paddingLeft: "calc(0.25rem * 3)",
    paddingRight: "calc(0.25rem * 3)",
    paddingTop: "calc(0.25rem * 2)",
    paddingBottom: "calc(0.25rem * 2)",
    textAlign: "left",
  },
  launcherSelected: {
    backgroundColor: tokens.colorSurfaceHover,
    color: tokens.fg,
  },
  launcherIdle: {
    color: {
      default: tokens.fg75,
      ":hover": tokens.fg,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  closeHovered: {
    opacity: 1,
  },
  launcherIcon: {
    color: "inherit",
  },
  lucideScale: {
    display: "block",
    verticalAlign: "middle",
    scale: constants.iconScale,
    transformOrigin: "center",
  },
});
