import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
  span14: {
    display: "inline-block",
    height: "calc(0.25rem * 6)",
    width: "calc(0.25rem * 6)",
    borderTopLeftRadius: "calc(infinity * 1px)",
    borderTopRightRadius: "calc(infinity * 1px)",
    borderBottomRightRadius: "calc(infinity * 1px)",
    borderBottomLeftRadius: "calc(infinity * 1px)",
    backgroundColor: tokens.hover,
  },
  aside39: {
    position: "sticky",
    display: "flex",
    top: "0px",
    height: "100%",
    borderRightStyle: "solid",
    borderRightWidth: "1px",
    borderTopColor: tokens.border,
    borderRightColor: tokens.border,
    borderBottomColor: tokens.border,
    borderLeftColor: tokens.border,
    backgroundColor: tokens.sidebarBg,
    flexDirection: "column",
    flexShrink: 0,
    zIndex: 40,
    overflowX: "hidden",
    overflowY: "hidden",
  },
  div42: {
    display: "flex",
    minHeight: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    flexDirection: "column",
    overflowX: "hidden",
    overflowY: "hidden",
    opacity: "100%",
  },
  div43: {
    position: "sticky",
    top: "0px",
    zIndex: 50,
    display: "flex",
    height: constants.toolbarHeight,
    flexShrink: 0,
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
    backgroundColor: tokens.sidebarBg,
    paddingLeft: "calc(0.25rem * 2)",
    paddingRight: "calc(0.25rem * 2)",
  },
  button46: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "flex",
    height: "calc(0.25rem * 7)",
    width: "calc(0.25rem * 7)",
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "0.5rem",
    borderTopRightRadius: "0.5rem",
    borderBottomRightRadius: "0.5rem",
    borderBottomLeftRadius: "0.5rem",
    color: {
      default: tokens.hl2,
      ":hover": tokens.fg,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  panelleftfilled50: {
    display: "block",
    verticalAlign: "middle",
    height: "calc(0.25rem * 3)",
    width: "calc(0.25rem * 3)",
  },
  button70: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    marginLeft: "auto",
    display: "flex",
    height: "calc(0.25rem * 7)",
    width: "calc(0.25rem * 7)",
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
    color: {
      default: tokens.hl2,
      ":hover": tokens.fg,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  searchicon74: {
    height: "calc(0.25rem * 4)",
    width: "calc(0.25rem * 4)",
  },
  sidebarScroller: {
    scrollbarWidth: "none",
    display: { default: "flex", "::-webkit-scrollbar": "none" },
    minHeight: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    flexDirection: "column",
    rowGap: constants.sidebarRowGap,
    columnGap: constants.sidebarRowGap,
    overflowX: "hidden",
    overflowY: "auto",
    paddingLeft: constants.sidebarPaddingX,
    paddingRight: constants.sidebarPaddingX,
    paddingTop: "calc(0.25rem * 0.5)",
    paddingBottom: "calc(0.25rem * 0.5)",
    contain: "layout paint",
  },
  button80: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "flex",
    height: constants.sidebarRowHeight,
    flexShrink: 0,
    alignItems: "center",
    rowGap: "calc(0.25rem * 2)",
    columnGap: "calc(0.25rem * 2)",
    borderTopLeftRadius: constants.sidebarRowRadius,
    borderTopRightRadius: constants.sidebarRowRadius,
    borderBottomRightRadius: constants.sidebarRowRadius,
    borderBottomLeftRadius: constants.sidebarRowRadius,
    paddingLeft: "calc(0.25rem * 2)",
    paddingRight: "calc(0.25rem * 2)",
    color: {
      default: tokens.fg85,
      ":hover": tokens.fg,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  squarepen84: {
    height: "calc(0.25rem * 4)",
    width: "calc(0.25rem * 4)",
    flexShrink: 0,
    opacity: "70%",
  },
  span87: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "left",
    fontSize: constants.fsMd,
    fontWeight: 400,
  },
  div109: {
    flexShrink: 0,
    backgroundColor: tokens.sidebarBg,
    paddingLeft: constants.sidebarPaddingX,
    paddingRight: constants.sidebarPaddingX,
    paddingBottom: "calc(0.25rem * 2)",
    paddingTop: "0.25rem",
  },
  div120: {
    display: "flex",
    height: constants.sidebarRowHeight,
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
  },
  div121: {
    display: "flex",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    alignItems: "center",
    rowGap: "calc(0.25rem * 2.5)",
    columnGap: "calc(0.25rem * 2.5)",
    paddingLeft: "calc(0.25rem * 2)",
    paddingRight: "calc(0.25rem * 2)",
    paddingTop: "0.25rem",
    paddingBottom: "0.25rem",
    textAlign: "left",
  },
  span123: {
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: constants.fsMd,
    color: tokens.fg,
  },
  span128: {
    display: "flex",
    height: "calc(0.25rem * 7)",
    width: "calc(0.25rem * 7)",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    color: tokens.fg40,
  },
  smartphone132: {
    height: "calc(0.25rem * 3.5)",
    width: "calc(0.25rem * 3.5)",
  },
  historyStepper: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "flex",
    height: "calc(0.25rem * 6)",
    width: "calc(0.25rem * 6)",
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
    color: {
      default: tokens.hl2,
      ":hover": tokens.fg,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  lucideScale: {
    display: "block",
    verticalAlign: "middle",
    scale: constants.iconScale,
    transformOrigin: "center",
  },
});
