import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
  section58: {
    display: "flex",
    minHeight: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    flexDirection: "column",
  },
  div59: {
    scrollbarWidth: "none",
    display: { default: "flex", "::-webkit-scrollbar": "none" },
    height: "calc(0.25rem * 9)",
    flexShrink: 0,
    alignItems: "center",
    rowGap: "calc(0.25rem * 0.5)",
    columnGap: "calc(0.25rem * 0.5)",
    overflowX: "auto",
    paddingLeft: "calc(0.25rem * 2)",
    paddingRight: "calc(0.25rem * 2)",
    fontSize: constants.fsSm,
    color: tokens.dim,
  },
  span60: {
    flexShrink: 0,
    borderTopLeftRadius: "0.375rem",
    borderTopRightRadius: "0.375rem",
    borderBottomRightRadius: "0.375rem",
    borderBottomLeftRadius: "0.375rem",
    paddingLeft: "calc(0.25rem * 1.5)",
    paddingRight: "calc(0.25rem * 1.5)",
    color: tokens.dim,
  },
  div64: {
    display: { default: null, "::-webkit-scrollbar": "none" },
    scrollbarWidth: "none",
    minHeight: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflowY: "auto",
  },
  span78: {
    position: "absolute",
    top: "0.25rem",
    bottom: "0.25rem",
    left: "0px",
    width: "calc(0.25rem * 0.5)",
    borderTopLeftRadius: "calc(infinity * 1px)",
    borderTopRightRadius: "calc(infinity * 1px)",
    borderBottomRightRadius: "calc(infinity * 1px)",
    borderBottomLeftRadius: "calc(infinity * 1px)",
    backgroundColor: tokens.link,
  },
  span81: {
    display: "flex",
    height: "calc(0.25rem * 3)",
    width: "calc(0.25rem * 3)",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
  },
  chevrondown82: {
    height: "calc(0.25rem * 3)",
    width: "calc(0.25rem * 3)",
  },
  chevronright86: {
    height: "calc(0.25rem * 3)",
    width: "calc(0.25rem * 3)",
    opacity: "0%",
  },
  button91: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "flex",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
    textAlign: "left",
  },
  folder97: {
    display: "block",
    verticalAlign: "middle",
    height: "calc(0.25rem * 3.5)",
    width: "calc(0.25rem * 3.5)",
    flexShrink: 0,
    color: tokens.dim,
  },
  span103: {
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  treeRow: {
    position: "relative",
    display: "flex",
    width: "100%",
    alignItems: "center",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
    borderTopLeftRadius: "0.25rem",
    borderTopRightRadius: "0.25rem",
    borderBottomRightRadius: "0.25rem",
    borderBottomLeftRadius: "0.25rem",
    paddingTop: "calc(0.25rem * 0.5)",
    paddingBottom: "calc(0.25rem * 0.5)",
    textAlign: "left",
    fontSize: constants.fsSm,
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  treeRowActive: {
    backgroundColor: tokens.colorSelected,
    fontWeight: 500,
    color: tokens.fg,
  },
  treeRowIdle: {
    color: tokens.dim,
  },
  fileIcon: {
    height: "calc(0.25rem * 3.5)",
    width: "calc(0.25rem * 3.5)",
    flexShrink: 0,
  },
  fileCode: {
  },
  fileData: {
    color: tokens.ok,
  },
  fileDocument: {
    color: tokens.fg,
  },
  fileMedia: {
    color: tokens.err,
    opacity: "70%",
  },
  fileNeutral: {
    color: tokens.dim,
  },
  fileScript: {
    color: tokens.warn,
  },
  treeIndent: (directory: boolean) => ({
    paddingLeft: directory ? "8px" : "20px",
    paddingRight: "8px",
  }),
  lucideScale: {
    display: "block",
    verticalAlign: "middle",
    scale: constants.iconScale,
    transformOrigin: "center",
  },
});
