import * as stylex from "@stylexjs/stylex";
import { constants, depth, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
  demo: {
  },
  p504: {
    position: "absolute",
    width: "1px",
    height: "1px",
    paddingTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    marginTop: "-1px",
    marginRight: "-1px",
    marginBottom: "-1px",
    marginLeft: "-1px",
    overflowX: "hidden",
    overflowY: "hidden",
    clipPath: "inset(50%)",
    whiteSpace: "nowrap",
    borderTopWidth: 0,
    borderRightWidth: 0,
    borderBottomWidth: 0,
    borderLeftWidth: 0,
  },
  demoViewport: {
  },
  demoApp: {
  },
  div520: {
    display: "flex",
    minHeight: "0px",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflowX: "hidden",
    overflowY: "hidden",
    backgroundColor: tokens.agentBg,
  },
  div522: {
    display: "flex",
    height: "100%",
    minHeight: "0px",
    width: "100%",
    flexDirection: "column",
    color: tokens.fg,
  },
  div523: {
    position: "relative",
    display: "flex",
    minHeight: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  section524: {
    position: "relative",
    display: "flex",
    minHeight: "0px",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    flexDirection: "column",
    backgroundColor: tokens.agentBg,
  },
  div532: {
    position: "relative",
    display: "flex",
    minHeight: "0px",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  agentChatScroller: {
    display: { default: null, "::-webkit-scrollbar": "none" },
    scrollbarWidth: "none",
    minHeight: "0px",
    minWidth: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflowY: "auto",
    backgroundColor: tokens.agentBg,
    paddingLeft: {
      default: "calc(0.25rem * 4)",
      "@media (width >= 40rem)": "calc(0.25rem * 5)",
    },
    paddingRight: {
      default: "calc(0.25rem * 4)",
      "@media (width >= 40rem)": "calc(0.25rem * 5)",
    },
    paddingBottom: "0px",
    paddingTop: "calc(0.25rem * 2)",
    overflowAnchor: "none",
    overscrollBehavior: "contain",
    scrollbarGutter: "stable",
  },
  agentThreadShell: {
    marginLeft: "auto",
    marginRight: "auto",
    display: "flex",
    flexDirection: "column",
  },
  div561: {
    height: "calc(0.25rem * 2)",
  },
  div566: {
    scrollbarWidth: "none",
    display: { default: "flex", "::-webkit-scrollbar": "none" },
    minHeight: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    overflowY: "auto",
    backgroundColor: tokens.agentBg,
    paddingLeft: "calc(0.25rem * 6)",
    paddingRight: "calc(0.25rem * 6)",
    paddingBottom: "calc(0.25rem * 10)",
    paddingTop: "calc(0.25rem * 2)",
  },
  agentThreadShell2: {
    marginLeft: "auto",
    marginRight: "auto",
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
  },
  div568: {
    display: "flex",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    rowGap: "calc(0.25rem * 3)",
    columnGap: "calc(0.25rem * 3)",
    textAlign: "center",
  },
  p569: {
    maxWidth: "24ch",
    fontSize: "clamp(1.45rem, 2.6vw, 2.1rem)",
    fontWeight: 600,
    lineHeight: 1.22,
    letterSpacing: "-0.02em",
    color: tokens.fg90,
  },
  p572: {
    fontSize: constants.fsXl,
    color: tokens.dim,
  },
  element584: {
    position: "relative",
    zIndex: 100,
    flexShrink: 0,
    backgroundColor: "transparent",
    paddingLeft: {
      default: "calc(0.25rem * 3)",
      "@media (width >= 40rem)": "calc(0.25rem * 5)",
    },
    paddingRight: {
      default: "calc(0.25rem * 3)",
      "@media (width >= 40rem)": "calc(0.25rem * 5)",
    },
    paddingBottom: "calc(0.25rem * 2)",
    paddingTop: "0px",
  },
  agentComposerBox: {
    position: "relative",
    zIndex: 10,
    marginLeft: "auto",
    marginRight: "auto",
    width: {
      default: "100%",
      "@media (width >= 40rem)": "90%",
    },
    maxWidth: "calc(42rem * 0.9)",
    overflowX: "visible",
    overflowY: "visible",
    borderTopLeftRadius: constants.composerRadius,
    borderTopRightRadius: constants.composerRadius,
    borderBottomRightRadius: constants.composerRadius,
    borderBottomLeftRadius: constants.composerRadius,
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopColor: tokens.border,
    borderRightColor: tokens.border,
    borderBottomColor: tokens.border,
    borderLeftColor: tokens.border,
    backgroundColor: tokens.composer,
    boxShadow: constants.composerElevation,
    ["cornerShape"]: "superellipse(1.5)",
  },
  div611: {
    display: "flex",
    minHeight: "calc(0.25rem * 9)",
    alignItems: "center",
    rowGap: "calc(0.25rem * 0.5)",
    columnGap: "calc(0.25rem * 0.5)",
    backgroundColor: "transparent",
    paddingLeft: "calc(0.25rem * 2)",
    paddingRight: "calc(0.25rem * 2)",
    paddingBottom: "calc(0.25rem * 2)",
    paddingTop: "0px",
    fontSize: "0.75rem",
  },
  button614: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "inline-flex",
    height: "calc(0.25rem * 7)",
    minHeight: "calc(0.25rem * 7)",
    width: "calc(0.25rem * 7)",
    minWidth: "calc(0.25rem * 7)",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "calc(infinity * 1px)",
    borderTopRightRadius: "calc(infinity * 1px)",
    borderBottomRightRadius: "calc(infinity * 1px)",
    borderBottomLeftRadius: "calc(infinity * 1px)",
    color: {
      default: tokens.hl2,
      ":hover": tokens.fg,
    },
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
  },
  plus618: {
    height: "calc(0.25rem * 4)",
    width: "calc(0.25rem * 4)",
  },
  div620: {
    marginLeft: "auto",
    display: "flex",
    minWidth: "0px",
    flexShrink: 1,
    alignItems: "center",
    rowGap: "calc(0.25rem * 0.5)",
    columnGap: "calc(0.25rem * 0.5)",
  },
  button624: {
    lineHeight: 1.5,
    display: "inline-flex",
    height: "30px",
    minHeight: "30px",
    minWidth: "0px",
    maxWidth: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    rowGap: "0.25rem",
    columnGap: "0.25rem",
    borderTopLeftRadius: "0.5rem",
    borderTopRightRadius: "0.5rem",
    borderBottomRightRadius: "0.5rem",
    borderBottomLeftRadius: "0.5rem",
    backgroundColor: {
      default: "transparent",
      ":hover": tokens.hover,
    },
    paddingLeft: "calc(0.25rem * 2)",
    paddingRight: "calc(0.25rem * 1.5)",
    fontSize: constants.fsBase,
    whiteSpace: "nowrap",
    color: {
      default: tokens.fg85,
      ":hover": tokens.fg,
    },
  },
  span628: {
    minWidth: "0px",
    maxWidth: "180px",
    overflowX: "hidden",
    overflowY: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "left",
  },
  chevrondown635: {
    pointerEvents: "none",
    height: "calc(0.25rem * 3.5)",
    width: "calc(0.25rem * 3.5)",
    flexShrink: 0,
    color: tokens.dim,
  },
  button640: {
    fontSize: constants.fsSm,
    lineHeight: 1.5,
    display: "inline-flex",
    height: "30px",
    minHeight: "30px",
    width: "30px",
    minWidth: "30px",
    flexShrink: 0,
    alignItems: "center",
    justifyContent: "center",
    borderTopLeftRadius: "calc(infinity * 1px)",
    borderTopRightRadius: "calc(infinity * 1px)",
    borderBottomRightRadius: "calc(infinity * 1px)",
    borderBottomLeftRadius: "calc(infinity * 1px)",
    backgroundColor: {
      default: tokens.fg,
      ":disabled": tokens.hl3,
    },
    color: tokens.bg,
    transitionProperty: "opacity",
    opacity: {
      default: null,
      ":hover": "85%",
      ":disabled": "100%",
    },
  },
  arrowup644: {
    height: "calc(0.25rem * 4)",
    width: "calc(0.25rem * 4)",
    strokeWidth: 2.25,
  },
  agentComputerPanel: {
    height: "100%",
    position: "relative",
    display: "flex",
    minHeight: "0px",
    flexShrink: 0,
    flexDirection: "column",
    borderLeftStyle: "solid",
    borderLeftWidth: "1px",
    borderTopColor: tokens.border,
    borderRightColor: tokens.border,
    borderBottomColor: tokens.border,
    borderLeftColor: tokens.border,
    backgroundColor: tokens.colorPanel,
    boxShadow: `-1px 0 0 ${depth.hairline}, -8px 0 20px ${depth.far}`,
  },
  div738: {
    display: { default: null, "::-webkit-scrollbar": "none" },
    scrollbarWidth: "none",
    width: "100%",
    height: "100%",
    overflowY: "auto",
    backgroundColor: tokens.bg,
    paddingLeft: "calc(0.25rem * 5)",
    paddingRight: "calc(0.25rem * 5)",
    paddingTop: "calc(0.25rem * 8)",
    paddingBottom: "calc(0.25rem * 8)",
    color: tokens.fg,
  },
  div739: {
    marginLeft: "auto",
    marginRight: "auto",
    maxWidth: "48rem",
  },
  div740: {
    fontSize: constants.fsLg,
    fontWeight: 500,
    color: tokens.dim,
  },
  div743: {
    marginTop: "0.25rem",
    fontSize: constants.fsSm,
    color: tokens.dim,
  },
  section751: {
    display: "flex",
    minHeight: "0px",
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: "0%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: tokens.colorPanel,
    fontSize: "0.75rem",
    color: tokens.dim,
  },
  div787: {
    paddingTop: {
      default: "calc(0.25rem * 4)",
      "@media (width >= 40rem)": "calc(0.25rem * 6)",
    },
    paddingBottom: "0px",
  },
  div791: {
    paddingTop: "calc(0.25rem * 2)",
  },
  div796: {
    paddingTop: "calc(0.25rem * 2)",
    paddingBottom: "calc(0.25rem * 4)",
  },
  article797: {
    minWidth: "0px",
  },
  chatMarkdown: {
    whiteSpace: "pre-wrap",
  },
  div805: {
    paddingTop: {
      default: "calc(0.25rem * 4)",
      "@media (width >= 40rem)": "calc(0.25rem * 6)",
    },
    paddingBottom: "calc(0.25rem * 4)",
  },
  codexShimmerText: {
    fontSize: constants.fsBase,
    fontWeight: 400,
    lineHeight: "calc(0.25rem * 5)",
  },
  a844: {
    marginTop: "calc(0.25rem * 3)",
    display: "flex",
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    borderTopLeftRadius: "0.5rem",
    borderTopRightRadius: "0.5rem",
    borderBottomRightRadius: "0.5rem",
    borderBottomLeftRadius: "0.5rem",
    borderTopStyle: "solid",
    borderRightStyle: "solid",
    borderBottomStyle: "solid",
    borderLeftStyle: "solid",
    borderTopWidth: "1px",
    borderRightWidth: "1px",
    borderBottomWidth: "1px",
    borderLeftWidth: "1px",
    borderTopColor: tokens.border,
    borderRightColor: tokens.border,
    borderBottomColor: tokens.border,
    borderLeftColor: tokens.border,
    backgroundColor: {
      default: tokens.colorPanel,
      ":hover": tokens.hover,
    },
    boxShadow: {
      default: constants.panelElevation,
      ":hover": constants.panelElevationHover,
    },
    transitionProperty: "background-color, box-shadow",
    transitionDuration: "160ms",
    paddingLeft: "calc(0.25rem * 3)",
    paddingRight: "calc(0.25rem * 3)",
    paddingTop: "calc(0.25rem * 2.5)",
    paddingBottom: "calc(0.25rem * 2.5)",
    fontSize: constants.fsSm,
    fontWeight: 500,
    color: tokens.fg,
  },
  span847: {
    color: tokens.dim,
  },
  leadMessage: {
    paddingTop: {
      default: "calc(0.25rem * 4)",
      "@media (width >= 40rem)": "calc(0.25rem * 6)",
    },
    paddingBottom: "0px",
  },
  timelineMessage: {
    paddingTop: "calc(0.25rem * 2)",
    paddingBottom: "calc(0.25rem * 4)",
  },
  lucideScale: {
    display: "block",
    verticalAlign: "middle",
    scale: constants.iconScale,
    transformOrigin: "center",
  },
});
