import * as stylex from "@stylexjs/stylex";
import { constants, tokens } from "../styles/tokens.stylex.ts";

export const styles = stylex.create({
	div3: {
		display: "flex",
		minHeight: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
		flexDirection: "column",
	},
	div13: {
		paddingLeft: "calc(0.25rem * 2)",
		paddingRight: "calc(0.25rem * 2)",
		paddingTop: "0.25rem",
		paddingBottom: "0.25rem",
		fontSize: constants.fsXs,
		color: tokens.dim,
	},
	div39: {
		display: "flex",
		flexDirection: "column",
	},
	div40: {
		color: tokens.fg,
		opacity: "100%",
		position: "relative",
		display: "flex",
		height: constants.sidebarRowHeight,
		alignItems: "center",
		borderTopLeftRadius: constants.sidebarRowRadius,
		borderTopRightRadius: constants.sidebarRowRadius,
		borderBottomRightRadius: constants.sidebarRowRadius,
		borderBottomLeftRadius: constants.sidebarRowRadius,
		paddingLeft: "calc(0.25rem * 2)",
		paddingRight: "calc(0.25rem * 1.5)",
		transitionProperty: "color,background-color,opacity",
		backgroundColor: {
			default: "transparent",
			":hover": tokens.hover,
		},
	},
	button44: {
		fontSize: constants.fsSm,
		lineHeight: 1.5,
		display: "flex",
		minWidth: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
		alignItems: "center",
		rowGap: "calc(0.25rem * 2)",
		columnGap: "calc(0.25rem * 2)",
		paddingLeft: "0px",
		paddingRight: "calc(0.25rem * 8)",
		textAlign: "left",
	},
	span46: {
		position: "relative",
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		flexShrink: 0,
		opacity: "70%",
	},
	folder47: {
		display: "block",
		verticalAlign: "middle",
		position: "absolute",
		top: "0px",
		right: "0px",
		bottom: "0px",
		left: "0px",
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		opacity: "0%",
	},
	folderopen48: {
		display: "block",
		verticalAlign: "middle",
		position: "absolute",
		top: "0px",
		right: "0px",
		bottom: "0px",
		left: "0px",
		height: "calc(0.25rem * 3.5)",
		width: "calc(0.25rem * 3.5)",
		opacity: "100%",
	},
	span50: {
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		fontSize: constants.fsMd,
		fontWeight: 400,
	},
	span63: {
		minWidth: "0px",
		flexGrow: 1,
		flexShrink: 1,
		flexBasis: "0%",
		overflowX: "hidden",
		overflowY: "hidden",
		textOverflow: "ellipsis",
		whiteSpace: "nowrap",
		paddingLeft: "0px",
		paddingRight: "0px",
		textAlign: "left",
		fontSize: constants.fsMd,
	},
	span66: {
		paddingRight: "calc(0.25rem * 2)",
		fontSize: constants.fsXs,
		color: tokens.hl2,
	},
	focusedRow: {
		position: "relative",
		display: "flex",
		height: constants.sidebarRowHeight,
		alignItems: "center",
		borderTopLeftRadius: constants.sidebarRowRadius,
		borderTopRightRadius: constants.sidebarRowRadius,
		borderBottomRightRadius: constants.sidebarRowRadius,
		borderBottomLeftRadius: constants.sidebarRowRadius,
		paddingLeft: "calc(0.25rem * 2)",
		paddingRight: "0px",
		backgroundColor: tokens.active,
		color: tokens.fg,
		transitionProperty: "color,background-color,opacity",
	},
	idleRow: {
		position: "relative",
		display: "flex",
		height: constants.sidebarRowHeight,
		alignItems: "center",
		borderTopLeftRadius: constants.sidebarRowRadius,
		borderTopRightRadius: constants.sidebarRowRadius,
		borderBottomRightRadius: constants.sidebarRowRadius,
		borderBottomLeftRadius: constants.sidebarRowRadius,
		paddingLeft: "calc(0.25rem * 2)",
		paddingRight: "0px",
		color: {
			default: tokens.fg85,
			":hover": tokens.fg,
		},
		transitionProperty: "color,background-color,opacity",
		backgroundColor: {
			default: "transparent",
			":hover": tokens.hover,
		},
	},
});
