#!/usr/bin/env node
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import {
	HOMEPAGE_LINK_HEADER,
	agentDocuments,
} from "../src/agent/documents.ts";
import { markdownPages, redirects, routePaths } from "../src/domain/route.ts";

const root = fileURLToPath(new URL("..", import.meta.url)).replace(/\/$/, "");
const command = process.argv[2] ?? "write";
const documents = agentDocuments();
const markdown = documents.find(({ path }) => path.endsWith(".md"));
if (!markdown) throw new Error("agent document registry has no markdown document");

function headersFor(route, contentType, extra = []) {
	return {
		source: route,
		headers: [{ key: "Content-Type", value: contentType }, ...extra],
	};
}

const markdownExtra = [{ key: "Vary", value: "Accept" }];
const headers = [
	{
		source: "/",
		headers: [
			{ key: "Vary", value: "Accept" },
			{ key: "Link", value: HOMEPAGE_LINK_HEADER },
			{
				key: "Content-Signal",
				value: "search=yes, ai-input=yes, ai-train=yes",
			},
		],
	},
	headersFor("/(.*)\\.md", markdown.contentType, markdownExtra),
	...documents
		.filter(({ path }) => !path.endsWith(".md"))
		.map(({ path, contentType }) => headersFor(path, contentType)),
];

const redirectRules = Object.entries(redirects).map(([source, destination]) => ({
	source,
	destination,
	permanent: true,
}));
const rewrites = [
	{ source: "/.well-known/mcp", destination: "/api/mcp" },
	...routePaths
		.filter((source) => source !== "/")
		.map((source) => ({ source, destination: "/index.html" })),
	...(["developers", "about", "contact", "privacy"].map((name) => ({ source: `/${name}`, destination: `/${name}.html` }))),
];

const vercelBody = `${JSON.stringify(
	{ installCommand: "pnpm install --frozen-lockfile --ignore-scripts", headers, redirects: redirectRules, rewrites },
	null,
	"\t",
)}\n`;
const middlewareBody = `// Generated by scripts/vercel.mjs. Do not edit.
const redirects = ${JSON.stringify(redirects)};
const markdownByPath = new Map(${JSON.stringify([...markdownPages()])});
const HOMEPAGE_LINK_HEADER = ${JSON.stringify(HOMEPAGE_LINK_HEADER)};

function wantsMarkdown(acceptHeader) {
	return (
		acceptHeader.includes("text/markdown") &&
		!acceptHeader.includes("text/html")
	);
}

function markdownTokenCount(body) {
	return String(Math.max(1, Math.ceil(body.length / 4)));
}

// Vercel requires a statically analyzable matcher.
export const config = {
	matcher: "/(.*)",
};

export default async function middleware(request) {
	let url;
	try {
		url = new URL(request.url);
	} catch {
		return new Response("Invalid request URL\\n", {
			status: 400,
			headers: { "Content-Type": "text/plain; charset=utf-8" },
		});
	}
	const pathname =
		url.pathname !== "/" && url.pathname.endsWith("/")
			? url.pathname.slice(0, -1)
			: url.pathname;
	const redirect = redirects[pathname];
	if (redirect) {
		return Response.redirect(new URL(redirect, url.origin), 308);
	}
	const accept = request.headers.get("accept") ?? "";
	if (!wantsMarkdown(accept)) return;
	const markdownPath = markdownByPath.get(pathname);
	if (markdownPath === undefined) return;
	const upstream = await fetch(new URL(markdownPath, url.origin));
	if (!upstream.ok) return;
	const body = await upstream.text();
	const headers = {
		"Cache-Control": "public, max-age=0, must-revalidate",
		"Content-Type": "text/markdown; charset=utf-8",
		Vary: "Accept",
		"x-markdown-tokens": markdownTokenCount(body),
	};
	if (pathname === "/") {
		headers.Link = HOMEPAGE_LINK_HEADER;
	}
	return new Response(body, { status: 200, headers });
}
`;
const outputs = [
	{ path: `${root}/vercel.json`, body: vercelBody },
	{ path: `${root}/middleware.js`, body: middlewareBody },
];

if (command === "write") {
	for (const output of outputs) writeFileSync(output.path, output.body);
	console.log("wrote vercel.json and middleware.js");
} else if (command === "check") {
	const stale = outputs.filter(
		(output) => readFileSync(output.path, "utf8") !== output.body,
	);
	if (stale.length > 0) {
		console.error("Vercel outputs are stale; run pnpm vercel:manifest");
		process.exit(1);
	}
	console.log("Vercel outputs ok");
} else {
	console.error(`unknown command: ${command}`);
	process.exit(1);
}
